### ISSUE TITLE
Assigning regions to large numbers of cells

### ISSUE THREAD

**Issue by Coastal0** [gimli-org/gimli#105]
Hi guys.

I wanted to get your thoughts regarding assigning large numbers of cell data.

I've been trying to use @florian-wagner example with the solute-transport modelling to work out how cell-values are assigned. For example, once the solute concentration has been calculated, he somehow gets the values into an ERT mesh for forward modelling.

That is what I'd like to do.

I have (finally) got my concentration mesh in order by interpolating a list of values onto my point-cloud mesh.

e.g.
```
print(dataInterp)
<class 'pygimli.core._pygimli_.RVector'> 16568 [35000.0,...,200.0]

print(datamesh_pointcloud)
Mesh: Nodes: 8585 Cells: 16568 Boundaries: 25151
```
![upload](https://user-images.githubusercontent.com/25240257/32430006-2db647ac-c308-11e7-8fdd-33a8f7a0118e.png)

Now I'm trying to forward model the above setting.

The simple forward model example (i.e. from BERT) has few values on the rhomap, however assigning hundreds, to thousands, of values in a rhomap seems unnecessarily complicated. I've reduced the number of unique resistivity values down to 302, and could probably go further if required. However, it seems that a better option is probably available (e.g. florians example again).

Can someone please shed some light on this for me..?

**Comment by florian-wagner** [comment]
Hi @Coastal0,

that looks like a wonderful seawater instrusion. So far, so good.

You have two options to populate a mesh with subsurface parameters (e.g. resistivity):

1. creating regions in the mesh (with markers) and mapping values to each region (useful for simple and layered models for example)
2. give each cell an individual parameter (maximum flexibility)

So in your case, you should go for option 2. Forget about mapping. You can directly use your `dataInterp` RVector as the input for forward modelling when you call `ert.simulate(dataInterp)`.

**Comment by Coastal0** [comment]
Great. Thanks Florian.

I'm making the ERTmesh (#106) today, then hopefully I'll have a result to show!

**Comment by florian-wagner** [comment]
Hi @Coastal0,

in the picture you posted every cell has a value and `datamesh_pointcloud` has as many cells as your `dataInterp` vector. So that is suitable for simulation.

If that is just your parameter mesh and you have a different mesh for simulation (with larger boundaries for example), you need to interpolate to the mesh you want to simulate on.

This is demonstrated in the mesh interpolation tutorial (https://www.pygimli.org/_tutorials_auto/1_basics/plot_5-mesh_interpolation.html#sphx-glr-tutorials-auto-1-basics-plot-5-mesh-interpolation-py), but I guess you are already familar with interpolation between meshes, since you interpolated your concentration values. So you are very close.

**Comment by Coastal0** [comment]
I think I've just about nailed it.

Thanks again Florian. 

Looking forward to meeting you all one day!
