### ISSUE TITLE
marker view with pg.show()

### ISSUE THREAD

**Issue by frodo4fingers** [gimli-org/gimli#135]
### Problem description

hi florian 😃 
i really like the markers feature for pg.show() and tried to implement it in gimod. but somehow the MWE down below really messes things up when set 'markers=True'

### Your environment

**Operating system**: ArchLinux
**Python version**: 3.6.4
**pyGIMLi version**: 1.0.5+118.g26cb30d9
**Way of installation**: manual compilation from source

### Steps to reproduce
```python
import pygimli as pg
import pygimli.meshtools as mt
from matplotlib import pyplot as plt


polys = []
polys.append(mt.polytools.createWorld(start=[0, 0], end=[1, 1], marker=0))
polys.append(mt.polytools.createRectangle(start=[0.1, 0.1], end=[0.15, 0.15], marker=1))
polys.append(mt.polytools.createRectangle(start=[0.2, 0.2], end=[0.25, 0.25], marker=2))
polys.append(mt.polytools.createRectangle(start=[0.3, 0.3], end=[0.35, 0.35], marker=3))
polys.append(mt.polytools.createRectangle(start=[0.4, 0.4], end=[0.45, 0.45], marker=4))
polys.append(mt.polytools.createRectangle(start=[0.5, 0.5], end=[0.55, 0.55], marker=5))
polys.append(mt.polytools.createRectangle(start=[0.6, 0.6], end=[0.65, 0.65], marker=6))
polys.append(mt.polytools.createRectangle(start=[0.7, 0.7], end=[0.75, 0.75], marker=7))
polys.append(mt.polytools.createRectangle(start=[0.8, 0.8], end=[0.85, 0.85], marker=8))

poly = mt.polytools.mergePLC(polys)
# this view should not look the way it looks, i'm sure
pg.show(poly, markers=True)

mesh = mt.createMesh(poly)
pg.show(mesh, markers=1)
pg.show(mesh, markers=0)
pg.show(mesh, mesh.cellMarkers(), showMesh=1, label='Marker')

pg.wait()
```

there are no error prompts.

cheers :-)
friedrich

**Comment by florian-wagner** [comment]
Hi Friedrich,

thanks for your feedback. The circles were way too big. I now sized them according to the text labels rather than absolute (https://github.com/gimli-org/gimli/commit/896d9e45fbde77bb234fbbedb150ed307984faa0). However, your example is still tricky and boundary labels were probably hard to read already prior to my change, since each rectangle is quite small and the labels are drawn for each of its 4 edges.

So `pg.show(mesh, markers=True)` looks fine and gives:

![mesh_markers_true](https://user-images.githubusercontent.com/2799008/36634791-6852f952-19aa-11e8-8f7c-3fc76f1eb776.png)

But `pg.show(poly, markers=True)` gives:

![poly_markers_true](https://user-images.githubusercontent.com/2799008/36634794-7751dad6-19aa-11e8-8143-a3d6d7a68345.png)

Not quite sure how to deal with this. One could:
- color the boundaries and add a second boundary marker colormap, but then it gets quite colorful...
- check if all 4 edges of the rectangle have the same marker and only plot it once
- apply some smart text adjustment by using https://github.com/Phlya/adjustText

Any suggestions welcome.

**Comment by florian-wagner** [comment]
And then there's the text overlap of the area information in the colorbar...

**Comment by carsten-forty2** [comment]
I think this is solved and can be closed, if I'm wrong please open a new issue.
