### ISSUE TITLE
Retrieve pyGIMLi version is 'untagged'

### ISSUE THREAD

**Issue by Coastal0** [gimli-org/gimli#137]
### Problem description

I've just installed pyGIMLi via the windows installer to use with Anaconda (rather than WinPython). I wanted to check I had the right version installed by using `pygimli._version()`, which returns

```
import pygimli
pygimli.version()
0+untagged.1780.g86f2041 core: libgimli-0.9.7
```
### Your environment
Windows 10
Python 3.6
````
print(pygimli.__version__)
0+untagged.1780.g86f2041
````
Installed via win binary (but had the same problem with wheels)

**Comment by florian-wagner** [comment]
Hi @Coastal0, yes, we are aware of this. This is due to the current way of packaging on windows. @halbmy is working on a conda package for windows at the moment. Once that is up and running, there is no need to mix installers and wheels with conda and also the version tag will be transferred correctly. We can leave this issue open as a reminder.

**Comment by halbmy** [comment]
The binary installers for Windows (wheels and msi) are now also undergoing the setup process so that the version numbers for both are ok now (currently 1.0.6). Note that I just replaced the binary installers on https://github.com/gimli-org/gimli/releases/latest after testing both msi and whl. Note that we are focussing on Python 3.6 only but could provide installers for Python 3.5 as well. We favor Anaconda (against which pyGIMLi is built) but WinPython should work as well. Python 2 support is dropped by now.

Next step is to provide conda packages for Windows (see #85) in the near future.
