### ISSUE TITLE
[Question] Contours with pg.show()

### ISSUE THREAD

**Issue by Coastal0** [gimli-org/gimli#144]
Hi guys,

Is there an easy method to add contour lines within pygimli's pg.show() architecture?

The examples below include the desired results, but I can't replicate for my situation.
https://www.pygimli.org/_examples_auto/dc_and_ip/plot_mod-dc-2d.html#sphx-glr-examples-auto-dc-and-ip-plot-mod-dc-2d-py
https://www.pygimli.org/_tutorials_auto/2_modelling/plot_2-mod-fem.html#sphx-glr-tutorials-auto-2-modelling-plot-2-mod-fem-py

```
import pygimli as pg
import numpy as np

def discrete_cmap(N, base_cmap=None):
    """Create an N-bin discrete colormap from the specified input map"""

    # Note that if base_cmap is a string or None, you can simply do
    #    return plt.cm.get_cmap(base_cmap, N)
    # The following works for string, None, or a colormap instance:

    base = plt.cm.get_cmap(base_cmap)
    color_list = base(np.linspace(0, 1, N))
    cmap_name = base.name + str(N)
    return base.from_list(cmap_name, color_list, N)

pg.show(bPolyMesh, dInterp, fillContour=True, nLevs = 11, colorBar = True, cMap=discrete_cmap(11, 'jet'), showMesh=0)[0]
```
bPolyMesh and dInterp files are in the attached zip.
[pyGimli.zip](https://github.com/gimli-org/gimli/files/2355558/pyGimli.zip)

Another example might be; 
https://matplotlib.org/examples/pylab_examples/tricontour_demo.html

**Comment by florian-wagner** [comment]
Hi @Coastal0,

`pg.show` plots cell data per cell (i.e. colors each quadrangle or triangle) and plots node data as fields, i.e. with contours. If you want to plot cell data as a field, you could make use of `pg.cellDataToPointData` as such:

``` python
import pygimli as pg
mesh = pg.load("bPolyMesh.bms")
data = pg.load("dInterp.vector")
pg.show(mesh, pg.cellDataToPointData(mesh, data))
```
Hope this helps.

Best wishes,
Florian

**Comment by Coastal0** [comment]
That's great, thanks Florian. 

What controls are there for the contours? (e.g. thickness, color, alpha, dashes..)

I'd ideally like to have a near-continuous colour range with contours overlain at every 5000 mg/L (for example).

**Comment by florian-wagner** [comment]
Hi Alex,

for explanation: `pg.show` detects that the data is per node and calls `pg.mplviewer.drawField`, which (does not do anything now since contour plotting became available on triangular grids in MPL and just) calls `pg.mplviewer.drawMPLTri`, which in turn calls `plt.tricontourf`. The keyword arguments are passed along, which can be confusing since not every keyword argument is documented in each function... But if you look up the documentations of the individual functions, it should become clearer. Personally I would not mix contours and continuous range plots, but this is subjective.

A filled contour plot with the orders of magnitude looks reasnoable:

``` pyhton
pg.show(mesh, data_points, ax=ax, hold=True, label="Salinity (mg/l)", nLevs=5, cMin=3, cMax=30000, logScale=True)
```
![image](https://user-images.githubusercontent.com/2799008/45185452-169cd380-b1df-11e8-9037-53aaeafd9602.png)

but you can of course mix both plotting types and do whatever you want:

``` python
pg.show(mesh, data, ax=ax, hold=True, label="Salinity (mg/l)", cMin=3, cMax=30000, logScale=True)
pg.mplviewer.drawField(ax, mesh, data_points, cMin=3, nLevs=5, cMax=30000, logScale=True, fillContour=False, colors=["w","r","b","g"], linewidths=3, alpha=0.5)
```
![image](https://user-images.githubusercontent.com/2799008/45185498-46e47200-b1df-11e8-9197-4fd180cf53e8.png)

**Comment by Coastal0** [comment]
Thanks again Florian

**Comment by Coastal0** [comment]
Almost a month later, and I appreciate that this is almost certainly a matplotlib question, but I'd really like to know how to change those colorbar labels to integers...

I've tried:
`cb.ax.xaxis.set_ticklabels(cb.get_ticks().astype(int))
Out[130]: 
[Text(0,0,'360'),
 Text(0.25,0,'1138'),
 Text(0.5,0,'3599'),
 Text(0.75,0,'11384'),
 Text(1,0,'35999')]
'
...but it does nothing on the actual figure.

Any suggestions would be really helpful!

**Comment by halbmy** [comment]
Assume ax and cb are the return values for the image axes and the colorbar. 
One would think that we could simply use `cb.ax.ticklabel_format(style='plain')` 
https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.ticklabel_format.html
but for some reason (??) we use the FixedFormatter using a function prettyFloat
https://github.com/gimli-org/gimli/blob/50676bedc20b23027bd574fe0f37a23194fbe922/python/pygimli/mplviewer/utils.py#L64

So we either change chis or we adjust the ticklabels by hand:
```
xt = cb.ax.get_xticks()
xtl = cb.ax.get_xticklabels()
for i in range(len(xt)):
    value = cb.norm.inverse(xt[i])
    xtl[i].set_text("{:d}".format(int(value)))

cb.ax.set_xticklabels(xtl)
```
