### ISSUE TITLE
Questions about inversion using pybert

### ISSUE THREAD

**Issue by ksabor** [gimli-org/gimli#153]
Hello,

I have a couple of doubts and questions that I haven't succed to find an answer to concerning ERT inversion using pybert ertManager:
- using the method "pybert.ERTManager.inv.setOptimizedLambda(True)" implies setting the optimization of lambda by Lcurve starting from lambda given as a keyword of invert method?
- zWeight key word argument of the method ERTManager.inversion refers to the weight of the smoothness with respect to z direction or it is related to the mesh?
- If I well understood, the convergence criterion avialable in the function inversion.h is either the maximum number of iterations or a threshold of the variation between two iterations or a chi2 threshold ? 
- the regularization approach used by defauld is occam or Levenberg-Marquardt ? ( I think it is Levenberg-Marquardt since we only have lambda and not alphax, alphaz smoothness parameters in each direction)

Thanks in advance,
Sincerely,
Kawtar

**Comment by halbmy** [comment]
1. Yes, the optimum lambda procedure starts from the given lambda value and computes solutions for 30 different values, each 20% below the neighboring one, and looks at the curvature of the L-curve. We will rework this function with the development of the inversion frameworks. I recommend not using this feature but to set up lambda by yourself (or by the chi2=1 routine) so that the data are fitted within noise.
2. Yes, zWeight is the relative weight for a purely vertical boundary using its normal vector as explained in eq. (2) of Coscia et al. (2011). 
3. Absolutely correct.
4. The default regularization is (for a normal mesh) a smoothness operator of first order, i.e., an Occam inversion. It can be changed by setting the cType of the region manager or individual regions. 
See also the explanations given in the BERT pdf tutorial (for the command line version). Currently this is more powerful but we we will improve the Resistivity Manager.

Coscia, I., Greenhalgh, S., Linde, N., Doetsch, J. A., Marescot, L., Günther, T., Vogt, T. & Green, A. (2011):
3D crosshole ERT for aquifer characterization and monitoring of infiltrating river water. Geophysics 76(2),
G49-G59, doi:10.1190/1.3553003.

**Comment by halbmy** [comment]
To 4.: alpha values (as used by Constable and others) make only sense for regular grids. Here we have lambda and zWeight, so you could imagine lambda as alpha-x and alpha-z=lambda*w_z.

**Comment by ksabor** [comment]
Thanks a lot for your quick and detailed answers.

**Comment by ksabor** [comment]
Hello,

Always concerning inversion using pybert, I wanted to know if there is a way to check which convergnce critirium was fullfilled (I have cases where chi2 is far from 1, and the maximum number of iterations is not reached, I deduce that it is because between two iterations the model hasn't changed much) without having to deduce is there a way to get the history of the rms as we can get the history of model calculation ?

Thank you in advance,
Best regards,
Kawtar

**Comment by florian-wagner** [comment]
Hey @ksabor,

we will provide more informative output and means to access/save the status of each iteration with the framework and manager rework in pygimli 1.1. Until then, you can use the `inv` object provided by the `ERTManager` manually, rather than the calling high-level `ert.invert()` function as follows:

``` python
# Set some stuff
ert.inv.setLambda(100) # regularization strength
ert.inv.setDeltaPhiAbortPercent(0.5) # minimum percentage change between iterations
ert.inv.setMaxIter(30) # maximum number of iterations

# Run inversion with output
for i in range(ert.inv.maxIter()):
    ert.inv.oneStep()
    pg.boxprint("Iteration: %d | Chi^2: %.2f | RMS: %.2f%%" % (i,
                ert.inv.chi2(), ert.inv.relrms()))
    if ert.inv.chi2() <= 1.0:
        print("Done. Reached target data misfit of chi^2 <= 1.")
        break
    phi = ert.inv.getPhi()
    if i > 2:
        print("Phi / oldphi", phi / oldphi)
    elif (phi / oldphi > (1 - ert.inv.deltaPhiAbortPercent() / 100)):
        print("Done. Reached data fit criteria of delta phi < %.2f%%."
              % ert.inv.deltaPhiAbortPercent())
        break
    if i + 1 == ert.inv.maxIter():
        print("Done. Maximum number of iterations reached.")
    oldphi = phi
```

PS: Since we usually don't check closed issues, please consider open a new one for the new questions in the future.

**Comment by ksabor** [comment]
Thanks a lot @florian-wagner for your complet suggestion. It will be of a great help for me. 

Ps: I will do so next time :)
