### ISSUE TITLE
Move generation of data noise into an own class

### ISSUE THREAD

**Issue by m-weigand** [gimli-org/gimli#161]
Data noise should be handled in a new class (located in **pg.utils**).

- [ ] proper handling of RNG seeds
- [ ] add normally distributed noise to linear data 
- [ ] add noise to log-transformed data (as currently done for electric data)

## Plots

- [ ] noise distribution

**Comment by halbmy** [comment]
This issue is almost 2 years old without any activity, maybe because there is no real problem and no need for a dedicated class, maybe just a convenience function.

Adding normally (or logarithmically) distributed noise to data is a one-liner and setting seeds as well. There are some examples using it and there could be more. If you want to discuss, do so, otherwise I suggest closing the issue.
