### ISSUE TITLE
Synthetic traveltime tomography issue

### ISSUE THREAD

**Issue by Pbottelin** [gimli-org/gimli#200]
### Problem description

Hello,
I am facing an issue when I try some synthetic modelling of seismic traveltime tomography. I created a simple uniform, rectangle model with a circle inside. The inversion result is weird, as the raypaths seem correct (most of the rays at least) but the velocity result is wrong.

### Your environment

**Operating system**: Windows,
**Python version**: 3.7?
**pyGIMLi version**: v1.0.11-33
**Way of installation**: Conda package

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```
the code is attached in the 2d_tomo_synthetique.py file

```

### Expected behavior

To retrieve the fast body as a result of the tomography & to have nicer raypaths (some of them seem stuck at the surface, probably because there is no velocity gradient in the medium)

### Actual behavior

see figure 2 attached
[2D_tomo_synthetique.txt](https://github.com/gimli-org/gimli/files/3713176/2D_tomo_synthetique.txt)
![Figure_2](https://user-images.githubusercontent.com/34316345/66580262-65edca00-eb7e-11e9-945e-e725de2c3c0f.png)

```
Paste output here.
```

> Labels: inversion issue, measurement scheme issue, traveltime tomography

Thanks for your help! And for the work done!

**Comment by florian-wagner** [comment]
Hi @Pbottelin,

the problem is that you are using the forward mesh, which has two regions with different cell markers and also boundary markers, which are used as structural a-priori information in the inversion (no smoothing across the circle boundary). It is always a good idea if the inversion mesh is completely independent to avoid an "inverse crime", i.e. avoid that the structure (circle) you are trying to estimate is already part of the mesh. 

``` python
#mesh_inv = mesh_fwd ##same mesh for inv and fwd : to be changed!
mesh_inv = mt.createMesh(world, area=5)
```
![image](https://user-images.githubusercontent.com/2799008/66587056-fb428b80-eb89-11e9-9b13-4c24e52accfd.png)

**Comment by Pbottelin** [comment]
Hi Florian, and thanks for your quick and very accurate answer. I was aware of the "inverse crime" problem but I (stupidly) did not take into account the region/marker issue..
Anyway, thanks again! Let's play with the model..
