### ISSUE TITLE
Interface to pydistmesh

### ISSUE THREAD

**Issue by carsten-forty2** [gimli-org/gimli#22]
https://pypi.python.org/pypi/PyDistMesh/1.1

**Comment by carsten-forty2** [comment]
I think we should skip this .. the licence of distmesh is not compatible.

**Comment by halbmy** [comment]
Distmesh (matlab) and pyDistMesh are both GPL, I don't see why they are incompatible at all. I never meant integrating pydistmesh into pyGIMLi, but writing a wrapper so that any PLC can be send to pyDistMesh and gets the model back. The meshes are really nice, and more suited for typical layered structures. distmesh can even mesh mesh 3D surfaces, e.g. a sphere (BERT modelling paper example).

**Comment by halbmy** [comment]
Nevertheless, both distmesh and pydistmesh are not developed anymore (just like triangle is not developed anymore but widely used). 

smeshing (https://github.com/bast/smeshing) could be a more active project to look at.

**Comment by florian-wagner** [comment]
https://www.featool.com/grid/2018/03/06/Matlab-Mesh-Generation-Comparison.html
