### ISSUE TITLE
Mailing List: suggestion

### ISSUE THREAD

**Issue by Khalilsqu** [gimli-org/gimli#220]
I would like to suggest to create a mailing list for PyGimli users similar to what [ObsPy](https://github.com/obspy/obspy) has. We can learn a lot from all discussions going on in issues especially if related to helping and questions. It is quite hard to keep always an eye on bug track here at GitHub and differentiate whats is truly a bug or a question!

Thanks and best wishes

**Comment by halbmy** [comment]
I don't think an explicit mailing list makes sense. We have a project on researchgate https://www.researchgate.net/project/pyGIMLi-Geophysical-Inversion-and-Modelling-Library-in-Python where we can post news but obviously we have no time for that as well.

The git issue tracker is in my opinion the best way to stay updated to a project, once you have a github account and "Watch" the project you'll get notice. Typically issues are labeled (e.g. discussion, bug, documentation, question) so that you will know whether it can help you or not. Please look also to closed issues as they might show solutions for your problem at hand.
