### ISSUE TITLE
traveltime tomography with close geometry

### ISSUE THREAD

**Issue by mcardenass** [gimli-org/gimli#258]
### Problem description

I am undergoing a travel time tomography with a closed square array. Sources and receivers surround the target. Modify the example Crosshole traveltime tomography and it works fine. Now the problem is that I can't get representative results when I use experimental data as input (file in TOM format). At the output, the sources and receivers are projected in the lower part of the model.

### Your environment

**Operating system**:  MacOS 10.15.6
**Python version**: 3.7.8
**pyGIMLi version**: 1.1.0+0.g47c8d810 (with local changes)
**Way of installation**: e.g. Conda package,
### Steps to reproduce

I attach the code which runs with two input files. See the output figure to visualize the problem. Thanks for any hint
[casas.dat.txt](https://github.com/gimli-org/gimli/files/5212856/casas.dat.txt)
[casas.py.txt](https://github.com/gimli-org/gimli/files/5212857/casas.py.txt)
[casas.tom.txt](https://github.com/gimli-org/gimli/files/5212858/casas.tom.txt)

**Comment by halbmy** [comment]
I am inlining the code here to let others follow the issue
```Python
#Cross traveltime tomography
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics.traveltime import TravelTimeManager

from pygimli.physics.traveltime.importData import readTOMfile

pg.utils.units.quants['vel']['cMap'] = 'inferno_r'
################################################################################
# Next, we build the cross-tomography acquisition geometry with four shallow receivers.

# Acquisition parameters
bh_spacing = 32.0
bh_length = 32.0
sensor_spacing = 2.0

geom = mt.createRectangle(start=[0, (bh_length + 0)], end=[bh_spacing, 0.0],
                           marker=0)

x,y = np.loadtxt('casas.dat', unpack=True)
sensors=np.dstack([x,y])
sensors=sensors.reshape(-1,2)

for sen in sensors:
    geom.createNode(sen)

mesh = mt.createMesh(geom, quality=34, area=0.25)

model = np.array([1000., 2000., 500.])[mesh.cellMarkers()]
ax,_ = pg.show(mesh,model,
        label=pg.unit('vel'), cMap=pg.cmap('vel'), nLevs=3, logScale=False, hold=True)
ax.plot(sensors[:, 0], sensors[:, 1], "bo")

pg.wait()

###############################################################################
#  Read real data
tt = TravelTimeManager()
data = readTOMfile('casas.tom')
print(data)

tt.showData(data)
pg.wait()

###############################################################################

invmodel = tt.invert(data, mesh=mesh, secNodes=3, lam=1000, zWeight=1.0,
                     useGradient=True, verbose=True)
print("chi^2 = %.2f" % tt.inv.chi2())  # Look at the data fit

################################################################################

fig, ax = plt.subplots(1, 1, figsize=(8, 7), sharex=True, sharey=True)
ax.set_title("Inversion result")

tt.showResult(ax=ax, logScale=False, nLevs=3)
tt.drawRayPaths(ax=ax, color="0.8", alpha=0.3)
fig.tight_layout()
```
and the inversion result
![image](https://user-images.githubusercontent.com/7136401/93018930-dd6c7a80-f5d3-11ea-8547-bb79e184f124.png)

**Comment by halbmy** [comment]
I first saved the data using `data.save("casas.sgt", "s g t")` and quickly checked whether loading the data works. After a quick look I'd say it is ok, but please have a look at it in more detail. Unfortunately, the circular geometry of the sensors is lost because these are sorted after increasing x and y.

As the normal data plots are made for refraction geometries, I visualized the data following my ideas from #256 using the following code
```Python
dist = pg.physics.traveltime.ratools.shotReceiverDistances(data, full=True)
va = dist / data["t"]
ax, _ = pg.viewer.mpl.showDataContainerAsMatrix(
    data, "g", "s", va, full=True, label="apparent velocity (m/s)")
ax.set_ylabel("shot index")
ax.set_xlabel("geophone index")
```
![image](https://user-images.githubusercontent.com/7136401/93019847-e82a0e00-f5d9-11ea-9c7a-cbeb40d8dc3e.png)

Doesn't make he whole world easier but I guess there are a lot of very low apparent velocities that are below the speed of air, which does not make much sense to me. Most of them occur if shot and geophone are on the same side. Maybe these data do not make much sense and have to be thrown away.

**Comment by halbmy** [comment]
Anyway, the main point is the geometry: in pyGIMLi, the vertical direction is counting upwards which is why after the importing the y position is negative as seen in the sgt file:
```
72
# x y z
0	-31.86	0
0	-30.09	0
```
So the rectangle for the inversion must be from (0, -32) to (32, 0). Actually it doe not make sense to read the sensor positions from a different file as they are already in the data file. So I changed it into (reading the data earlier):
```
for sen in data.sensors():
    geom.createNode(sen)
```
so that the whole script reads
```Python
import matplotlib.pyplot as plt
import numpy as np

import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics.traveltime import TravelTimeManager

from pygimli.physics.traveltime.importData import readTOMfile

pg.utils.units.quants['vel']['cMap'] = 'inferno_r'
################################################################################
# Next, we build the cross-tomography acquisition geometry with four shallow receivers.

# Acquisition parameters
bh_spacing = 32.0
bh_length = 32.0
sensor_spacing = 2.0

geom = mt.createRectangle(start=[0, -(bh_length + 0)], end=[bh_spacing, 0.0],
                           marker=0)

data = readTOMfile('casas.tom')
print(data)
for sen in data.sensors():
    geom.createNode(sen)

mesh = mt.createMesh(geom, quality=34, area=0.25)

model = np.array([1000., 2000., 500.])[mesh.cellMarkers()]
ax, _ = pg.show(mesh)
ax.plot(pg.x(data.sensors()), pg.y(data.sensors()), "bo")
tt = TravelTimeManager()
# %%
invmodel = tt.invert(data, mesh=mesh, secNodes=3, lam=1000, zWeight=1.0,
                     useGradient=False, verbose=True)
print("chi^2 = %.2f" % tt.inv.chi2())  # Look at the data fit
# %% 
fig, ax = plt.subplots(1, 1, figsize=(8, 7), sharex=True, sharey=True)
ax.set_title("Inversion result")
tt.showResult(ax=ax, logScale=False, nLevs=3)
tt.drawRayPaths(ax=ax, color="0.8", alpha=0.3)
fig.tight_layout()
```
resulting in 
![image](https://user-images.githubusercontent.com/7136401/93020409-2a088380-f5dd-11ea-9307-e36c43bc4bfe.png)

The data fit is not really good, but I guess this has to do with the too large traveltime along the sides.

**Comment by mcardenass** [comment]
Thank you very much, I already understood the geometry problem. You're right, data with velocities less than airspeed should be reviewed or discarded. The objective is to analyze the irregularity of the substratum.
