### ISSUE TITLE
DECEM JOINT INVERSION

### ISSUE THREAD

**Issue by Abhilash2106** [gimli-org/gimli#260]
### Unable to run the code decem joint inversion

AttributeError                            Traceback (most recent call last)
<ipython-input-6-946e7d6ac7da> in <module>
      8 dataEM = fEM(model)
      9 for i in range(len(dataEM)):
---> 10     dataEM[i] += pg.randn(1)[0] * noiseEM

AttributeError: module 'pygimli' has no attribute 'randn'

### Your environment

**Operating system**: e.g. Windows,?
**Python version**: e.g. 3.6
**pyGIMLi version**: 
**Way of installation**: e.g.

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
import pygimli as pg
...
```

### Expected behavior

Tell us what should happen or what you want to achieve.

### Actual behavior

Tell us what happens instead and/or provide the output of your script.

```
Paste output here.
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
When filling an issue, please fill in the information about version number etc. so that we can follow the error. 

The example 
https://www.pygimli.org/_examples_auto/5_misc/plot_1_dcem.html#sphx-glr-examples-auto-5-misc-plot-1-dcem-py
runs both on pygimli 1.1.0 and 1.1.1. There should be a `pg.randn` function but it should rather be `pg.math.randn`. The loop is not really modern style, so you should better use
```
dataEM += pg.math.randn(len(dataEM)) * noiseEM
```
or, use the numpy randn function directly
```
dataEM += np.random.randn(len(dataEM)) * noiseEM
```
and accordingly for DC
```
dataDC *= 1. + np.random.randn(len(dataDC)) * noiseDC / 100.
```
I updated the example accordingly.
