### ISSUE TITLE
3D travel time tomography - issues when computing the jacobian matrix

### ISSUE THREAD

**Issue by MymyLaj** [gimli-org/gimli#271]
### Problem description
Hello,

I am trying to invert a 3D seismic data, acquired in a site where there are topographic variations. Following the discussion #218 I created the mesh via BERT, and imported it via meshtool.readTetgen : mesh = mt.readTetgen('mesh/mesh'). 

However, I have three questions/issues :

- The mesh seems too large, and I am not sure weather this excessive mesh would be a problem for the inversion ?
- I do not manage to export the gradient model in vtk, only the mesh is exported, but not the velocity model, as reported in issue #242 in the case of resistivity models -> is there an equivalent of ertinv.saveResult() for a seismic velocity model ?
- The computation of the jacobian does not work, it is probably for a very obvious reason, but I cannot find it… 

I put the data, mesh and script together here: [Viella_TTT.zip](https://github.com/gimli-org/gimli/files/5665415/Viella_TTT.zip)
Thank you very much in advance !

### Your environment

**Operating system**: Linux
**Python version**: 3.7
**pyGIMLi version**: 1.1.0+0.g47c8d810 (with local changes)
**Way of installation**:  Conda package

### Steps to reproduce

When I run the following lines: 
```python
fop = pg.core.TravelTimeDijkstraModelling(mesh, data)
fop.createJacobian(mesh)
...
```
I get the following error: 
```python
ArgumentError: Python argument types in
    TravelTimeDijkstraModelling.createJacobian(TravelTimeDijkstraModelling, Mesh)
did not match C++ signature:
    createJacobian(TravelTimeDijkstraModelling_wrapper {lvalue}, GIMLI::Vector<double> model, GIMLI::Vector<double> resp)
    createJacobian(GIMLI::TravelTimeDijkstraModelling {lvalue}, GIMLI::Vector<double> model, GIMLI::Vector<double> resp)
    createJacobian(GIMLI::TravelTimeDijkstraModelling {lvalue}, GIMLI::SparseMapMatrix<double, unsigned long> {lvalue} jacobian, GIMLI::Vector<double> slowness)
    createJacobian(TravelTimeDijkstraModelling_wrapper {lvalue}, GIMLI::Vector<double> slowness)
    createJacobian(GIMLI::TravelTimeDijkstraModelling {lvalue}, GIMLI::Vector<double> slowness)
...
```

**Comment by carsten-forty2** [comment]
The native forward operator (FOP) is supposed to calculate the Jacobian matrix only if you initialized the FOP with a mesh with numbered cell markers for each parameter. 

You should use the `physics.TravelTimeManager` if you want to calculate the Jacobian or use any conveniance methods. 
The Manager will feed the FOP with the mesh and will take care of the cell numbering (please see the traveltime examples.)
The Manager also have the `saveResult` method which creates velocity.vtk with the velocity model values from the last inversion run.

If you want to call `createJacobian` manually on the FOP or the Manager, you need to provide a model vector instead of a mesh.

**Comment by MymyLaj** [comment]
Thank you very much for your answer ! 
After a few trials, I think that I understand how I should use either the Traveltime Manager or the Forward Operator. However, I am still stuck at the same stage of jacobian computation.

After importing data and mesh, I create a model, as before, and call the FOP : 

```
vel = 350 + (1819-pg.z(mesh.cellCenters())) * 10
fop = pg.core.TravelTimeDijkstraModelling(mesh, data)
fop.createJacobian(vel)
```

The kernel then crashes and restarts automatically.

I realized another test with the TravelTime Manager : 

```
tt = TravelTimeManager(data)
tt.inv.inv.setRecalcJacobian(True)
invmodel = tt.invert(data, mesh=mesh, secNodes=3, lam=10, zWeight=1.0, useGradient=True, 	vTop=500, vBottom=5000, verbose=True, noiseLevel=0.001, noiseAbs=1e-5)
```

The kernel crashes in the inversion (`slowness = super().invert(data, mesh, **kwargs)`)

Since I do not get any error, I don’t really know what the issue is. Do you have an idea ? Am I still using the FOP and manager the wrong way ? 
Thanks again !

**Comment by carsten-forty2** [comment]
Without digging to deep in your example ...

Your mesh contains 2 regions, an outer boundary region with Marker == 1 and a region supposed to be the parameter domain with Marker == 2. You don't need this outer part for Traveltime inversion so I recommend to extract the inner part and reduce the problem size. You can do this with:
```
mesh = mesh.createSubMesh(mesh.cells(mesh.cellMarkers()==2))
```

Your `vel` array contains 'nan' values because the outer part of the mesh brings z values larger then `1892` which broke the `np.log2`. This can also be fixed by vanishing region 1.
You can take a look at it with:
```
mesh['vel'] = vel
mesh.exportVTK('test')
```
Unfortunately, `exportVTK` wrote also the 'nan' values into the vtk file, but paraview refuse them later. I added a warning (4d7613bf) to avoid this pitfall in the future 

The mesh for region 2 still contains '66666' parameter cells, which might also a little to much for higher accuracy calculation especial with some secondary nodes. I recommend to start with reducing the local mesh refinement near the sensor points to create a coarser mesh for becoming familiar with the Traveltime toolchain. 
You can increase the mesh density later to find the boundaries of your hardware.

If you use windows os try to add the -u parameter to the python call. For some reasons the terminal output cuts down a lot of messages like errors or warnings.

**Comment by MymyLaj** [comment]
Thank you so much for your help! Everything seems to work fine now !

**Comment by Michaelj100** [comment]
Hello Senior Collegues,
Please I'm faced with almost a similar issue.

My case was trying to render my result mesh was created, and the script was to build the 3D model inside the imported mesh. However, the exported VTK shows the velocity wasn't distributed across the mesh rather it indicated the whole 3D mesh having one velocity which was the starting velocity.
I also noticed that the number of inversion iterations was set at a a given number of time but the inversion stops just after 3 iterations.

I'd be glad if you could me with ideas

[MymeshImport2.py](https://github.com/user-attachments/files/28215907/MymeshImport2.py)

**Comment by halbmy** [comment]
Apparently there is no good convergence, but we cannot tell you much without seeing data or mesh. Please have a look at the apparent velocity distribution and make sure the mesh has constant markers.

**Comment by Michaelj100** [comment]
Thanks a lot. I will have a closer look into that, but in the mean time, here is the dataset and mesh included. 

[M_3D.zip](https://github.com/user-attachments/files/28303131/M_3D.zip)

> Apparently there is no good convergence, but we cannot tell you much without seeing data or mesh. Please have a look at the apparent velocity distribution and make sure the mesh has constant markers.
