### ISSUE TITLE
[question] Get xyz from raw ERT data?

### ISSUE THREAD

**Issue by viictorjs** [gimli-org/gimli#283]
Hello!

I have this gimli file of ERT data with topography I created using the exportData function from pybert
[ERT_test.txt](https://github.com/gimli-org/gimli/files/5867818/ERT_test.txt)

I'm plotting the raw data using the following approach

```python
from pygimli.physics.ert import show
import pybert as pb
import matplotlib.pyplot as plt

data = pb.importData("ERT_test.txt")
show(data) #plot the apparent resistivity points (distance x investigation level)
plt.plot()
...
```

Is there a function I can use to export a 3-column file (distance, elevation, apparent resistivity) of the raw data? 

Appreciate any help!

**Comment by halbmy** [comment]
`pb.importData` is for importing external file formats e.g. from instruments or other software, among these ascii output of data which is what txt is usually pointing at. However, the file you have is directly in standard format, so you can just load it by `data=pg.DataContainerERT(...)`

ERT data do not have a single "data position", they are always related to the position of the four electrodes. So there is no way of exporting data in a simple three-column file. (Otherwise the ERT format would be easier.) If you are referring to the pseudosection itselt, please note that is just a colored table of data. The y axis cannot be associated to the measuring depth, it just represents a typical way of sorting. We avoid terms like pseudodepth as data are integral values.

**Comment by viictorjs** [comment]
@halbmy thank you for the quick reply!

My goal in obtaining this information was to assign a polygon and use it to blank out areas outside the positions where I have no actual data points. My final model would have a trapezoidal shape that approximately follows the distribution of the actual data points in the pseudosection. I'd use something like Scipy's ConvexHull for that...

**Comment by halbmy** [comment]
OK, I consider the question being answered. Anything with data points considered as points in the subsurface seems strange to me, but anyway I'd be interested in the results of your ideas.
