### ISSUE TITLE
how to change pseudosection model ["question"]

### ISSUE THREAD

**Issue by RFauziahSM** [gimli-org/gimli#335]
### Problem description
Hi, everyone.
currently I'm still learning about pygimli, so please forgive my lack of knowledge about python.
I want to ask, in the following example [https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_02_ert_field_data.html#sphx-glr-examples-auto-3-dc-and-ip-plot-02-ert-field-data-py](url) 
how can I change the pseudosection model of the model data and response to have the same model size as the final model?
if required electrode spacing in pseudosection model, how do I add it to the code
this is my model 
![Lintasan1PseudoModele](https://user-images.githubusercontent.com/90299255/132621217-18d9287c-73db-4efc-8848-1cb4a9a6856f.png)
![Model Lintasan 1](https://user-images.githubusercontent.com/90299255/132621228-0ab91b68-89c2-419f-8620-32affb51560b.png)

but I want to change the pseudosection model so that it has the same model size as the final model like this (sorry if I use a model example from another software)
<img width="957" alt="1" src="https://user-images.githubusercontent.com/90299255/132621419-30ef970b-94c7-4e41-9407-067e6cfcc4b6.PNG">

### Your environment

**Operating system**: Linux 
**Python version**: 3.7
**pyGIMLi version**: Output of `print(pg.__version 1.1.1)`
**Way of installation**: Conda package

### Steps to reproduce

ert.showFit()
ert.showModel(mgr)

### Expected behavior
how to change pseudosection model

### Actual behavior

```
Paste output here.
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
A pseudosection is a coloured table of measurements where typically the x position of the measurement is a midpoint (of the M-N dipole or the whole array) is used to locate it on the x axis and some sort of depth penetration is used for the y axis. In some softwares (e.g. in res2dinv) a so-called "pseudodepth" is calculated for the latter which already provides some sort of a subsurface image and some sort of interpolation is done to fill the area between (in the above example white) points. However, in my opinion this can be very dangerous for non-experts as they might interpret this as subsurface image. The example shows nicely how misleading this can be.

Whereas for single standard arrays (e.g. Wenner) the points are evenly distributed (and thus an interpolation makes some sense), the points are very irregular if more complicated arrays (like multi-gradient) or mixed arrays (e.g. Wenner plus dipole-dipole) are used. As a result the pseudosections can become rather patchy and different data points have different areas of influence, e.g. outliers can dominate the image or be invisible. Every single quadrupole has a subsurface sensitivity that cannot be easily represented by a single point:
https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_05_ert_4_point_sensitivities.html

Therefore we prefer representing each measurement with a patch of even size using a systematic ordering. Different arrays types (or dipole lengths of the same type) are plotted beneath each other so that e.g. the Wenner data are separated from dipole-dipole data. 

The example data (Profile 1 in Müller et al. 2020, Fig. 8) below
![image](https://user-images.githubusercontent.com/7136401/132654033-60e66613-a302-4791-9e8d-460fe4d1e13b.png)
represents a combination Wenner-alpha (WA), dipole-dipole (DD) with single (DD-n), double (DD2-n), fourfold (DD4-n) and eightfold (DD8-n) as well as Wenner-beta (DDm-n), where m is the dipole length and n the dipole distance in unit electrode spacings. Any mixed interpolation of these data looks strange, outliers are easily recognizable and data quality can be assessed visually.

Müller, K., Polom, U, Winsemann, J., Steffen, H., Tsukamoto, S., Günther, T., Igel, J., Spies, T., Frechen, M., Franzke, H.-J. & Brandes, C. (2020): Structural style and neotectonic activity along the Harz Boundary Fault, northern Germany: a multimethod approach integrating geophysics, outcrop data and numerical simulations. Int. J. Earth Sciences 109(5), 1811-1835, doi:10.1007/s00531-020-01874-0.

**Comment by halbmy** [comment]
If your point is about using the same x axis and the same color scale in subplots, this can be easily done by:
```
kw = dict(cMin=1, cMax=50, cMap="Spectral_r")
fig, ax = plt.subplots(nrows=3, sharex=True)
pg.show(data, ax=ax[0], **kw)
pg.show(data, mgr.inv.response, ax=ax[1], **kw)
mgr.showResult(ax=ax[2], **kw)
```

**Comment by RFauziahSM** [comment]
Thanks for your answer. Finally, I better understand the pseudosection concept where the datum on the pygimli is represented by a rectangle located at the midpoint position and with increasing electrode spacing.

**Comment by RFauziahSM** [comment]
Thank you. I've tried the code with a few additions
`kw = dict(cMap="Spectral_r")
fig, ax = plt.subplots(3,1, sharex=False, figsize=(12.5,10.2))
pg.show(data, ax=ax[0], colorBar=False, label="", **kw)

ax[0].text(0.0, 1.03, "Measured Apparent Resistivity Pseudosection ",
                    transform=ax[0].transAxes,
                    horizontalalignment='left',
                    verticalalignment='center')
pg.show(data, ert.inv.response, ax=ax[1], colorBar=False, 
        label="", **kw)


ax[1].text(0.0, 1.03, "Calculated Apparent Resistivity Pseudosection",
                    transform=ax[1].transAxes,
                    horizontalalignment='left',
                    verticalalignment='center')

ert.showModel(mgr, cMin =4.84, cMax=69.98, ax=ax[2], **kw )
data = ert.inv.dataVals
resp = ert.inv.response
ax[2].text(0, 1.03, r"rrms: {0}%, $\chi^2$: {1}".format(
                pg.pf(pg.utils.rrms(data, resp)*100),
                pg.pf(ert.fw.chi2History[-1])),
                    transform=ax[2].transAxes,
                    horizontalalignment='left',
                    verticalalignment='center')`

and as a result, the models have the same size

**Comment by RFauziahSM** [comment]
Thank you. I've tried the code with a few additions

`kw = dict(cMap="Spectral_r")
fig, ax = plt.subplots(3,1, sharex=False, figsize=(12.5,10.2))
pg.show(data, ax=ax[0], colorBar=False, label="", **kw)

ax[0].text(0.0, 1.03, "Measured Apparent Resistivity Pseudosection ",
                    transform=ax[0].transAxes,
                    horizontalalignment='left',
                    verticalalignment='center')
pg.show(data, ert.inv.response, ax=ax[1], colorBar=False, 
        label="", **kw)


ax[1].text(0.0, 1.03, "Calculated Apparent Resistivity Pseudosection",
                    transform=ax[1].transAxes,
                    horizontalalignment='left',
                    verticalalignment='center')

ert.showModel(mgr, cMin =4.84, cMax=69.98, ax=ax[2], **kw )
data = ert.inv.dataVals
resp = ert.inv.response
ax[2].text(0, 1.03, r"rrms: {0}%, $\chi^2$: {1}".format(
                pg.pf(pg.utils.rrms(data, resp)*100),
                pg.pf(ert.fw.chi2History[-1])),
                    transform=ax[2].transAxes,
                    horizontalalignment='left',
                    verticalalignment='center')`

and the result, the size of the model is the same

**Comment by halbmy** [comment]
Very nice. It is good to have this clarification about pseudosections somewhere to link to.

Instead of the more complex `ax.text()` you could use `ax.set_title()`.

**Comment by RFauziahSM** [comment]
ok, i will change it, thank you
