### ISSUE TITLE
Improved pseudosection for the ERT

### ISSUE THREAD

**Issue by brianhavk** [gimli-org/gimli#380]
### Problem description

Hello everyone, I hope you are well.

I have a situation regarding the pseudosection that is generated from some data (Original.dat) as I need it to be displayed fully sorted from highest to lowest depth penetration (as it should be), which is not happening as you can see in the image of the generated pseudosection.

I have managed to sort the data by depth of penetration (Sorted.dat) based on the midpoint of the unconventional Dipole-Dipole array, in which for this data the first electrode is N and the last B; but in spite of managing to sort them it is still generating the pseudosection as I have commented.

I hope you can help me with this question, thank you very much in advance and I look forward to your answer.

[Data.zip](https://github.com/gimli-org/gimli/files/8367317/Data.zip)
![Pseudosection](https://user-images.githubusercontent.com/82900508/160532632-111bb33e-a0b1-43f0-a1d7-4ed2442e399e.png)

**Comment by halbmy** [comment]
Hello, I pseudosection is a coloured table of measurements in a logical order so that one is able to assess the structural quality of the data and to identiy outliers. I personally consider interpolation of data that are associated with a "depth point" very dangerous. This is why every data point is plotted as a rectangle of the same size, independent on how the data are sorted in the file. Of course one could discuss the ordering of the levels, e.g. we could interchange the dipole length (outer order) with the dipole distance (inner order) to have monotonic increase of penetration depth. You can try this out and make such a plot by means of some lines of Python code and it it looks interesting we could include this as an option. However, I would never mix Dipole-Dipole with Wenner data which are displayed under each other.

**Comment by brianhavk** [comment]
Hello again.
Interestingly, I am also working with the treatment of outliers and so it seemed pertinent to show the pseudosection linearly to the depth. Thanks to what you mentioned about "swapping the dipole length (outer order) with the dipole distance (inner order) to have a monotonic increase of the penetration depth" I was able to achieve the goal. Since I went from having "3 different DD arrays" to just 1 by adjusting the length and distance as you mentioned; I thank you for that.
![1](https://user-images.githubusercontent.com/82900508/161403007-d997ce87-cb1b-40be-96cc-a2397a43c8e8.png)

In achieving this, I had to average two profiles (I speak of profile as each data set for each depth) because they had the same "depth of penetration" and if I didn't do it one would overlap with the other.
![2](https://user-images.githubusercontent.com/82900508/161403008-30c28510-36c1-43e7-bfcb-6bbb46d433f3.png)

Additionally, I fixed the outlier seen in the 26.3-meter depth profile by using an approximation of the proximal values (from the other profiles).
![3](https://user-images.githubusercontent.com/82900508/161403015-124c8199-c025-4b53-8d16-537bdd6f0ee6.png)

It would be good to study what you say about the size of the rectangles as a thickness of the subsurface sample (different for each profile of course), but only as a study.
Thank you very much for your help.

**Comment by halbmy** [comment]
To make it clear again:
* there can be only one plotting routine for all (combinations of) arrays, none special for different arrays
* when plotting data of different array types, they need to go into one plot
* every rectangle should be plotted with the same size as they all represent one value
* there is no real depth (not even a maximum depth) for data points 
* even using "linear with depth" does not make sense as this depth spacing is irregular and would lead to overlaps or gaps
* your case is still simple (all DD) but when mixing different arrays any "depth-related" images will be confusing
* one can, however, discuss the ordering (dipole length vs. distance)

Assume measurements with the same dipole distance, e.g. 2-3-11-13 and 1-3-11-12 will probably have almost the same pentration depth but they cannot plotted onto each other. So they need to go in either a) different groups of dipole lengths or b) the same group of dipole distances, below each other.

**Comment by brianhavk** [comment]
I will take all these clarifications into account for future work. Thank you very much indeed.

As for the "maximum depth", I have to tell you in parts what it is. 
When I did the inversion of this data for the first time (indicating only the lambda value) I got an image with a paraDepth of 80 metres, which would be 0.4 * maximum range of the sensor (200 metres) as indicated, of course, on the [GIMLi Documentation.pdf](https://github.com/gimli-org/gimli/files/8499039/GIMLi.Documentation.pdf).

The problem is that it did not match the image of that data processed in the res2Dinv software. I apologise in advance for mentioning it here and for the image I will show below.
![Line3_Resistivity20it](https://user-images.githubusercontent.com/82900508/163656941-09e5ded8-bfeb-41f0-9953-cbd48c14e218.png)

To solve it, I studied the depth of investigation and the constants used for these arrays; arriving at Barker (1989) and resulting in the depths I assigned in the pseudosection. It would have been better if I had spoken as research depth from the beginning, again I apologise.

I would like then, with what you have told me, not to do the average and better to show the two extensions. 
These research depths for the pseudosection, I would rather call them, rather, pseudo-depths. Of course only for these special pyGIMLi plots, and with your approval.

P. D.: Sorry for the delay in replying, the image I showed had to be requested again and I found it too relevant to the discussion. 

References
Barker, R. D. (1989). Depth of investigation of collinear symmetrical four‐electrode arrays. GEOPHYSICS, 54(8), 1031–1037. https://doi.org/10.1190/1.1442728

**Comment by halbmy** [comment]
@Khalilsqu What you suggest is basically to use contour lines instead of filled polygons for both model and data representation. While this can be done easily for the model (see API documentation in `pg.viewer.mpl`), I suggest not using this for plotting ERT data as explained above, particularly not using any "pseudodepth" scheme. Every data point should be represented by the same area so that we clearly see outliers and do not suggest "smoothing" the data. In inversion, both data are discrete model vectors and in my opinion this should be back in mind especially for non-geophysicists.

**Comment by halbmy** [comment]
The original issue was about switching the ordering scheme of dipole lengths vs. dipole distances which indeed makes sense regarding penetration depth and data consistency. In the recent commit (#9c9f6d77) I introduced a keyword `switch` to achieve this result:

![image](https://user-images.githubusercontent.com/7136401/181456603-c3ddb8de-9487-4553-a3f4-67c9658e6fee.png)

However, I don't set this as default as this would break consistency to published images. Furthermore one cannot easily "count the gaps" between the ticks on the y axis so that is not fully clear which type of array it is. (Labelling every tick, on the other hand, might be bad for long profiles.)

**Comment by Khalilsqu** [comment]
Dear Prof. @halbmy,

I totally agree that the current approach is the best way forward. PyGimli has excellent flexibility, reproducibility, and expandability, exposing the underlying data, model, and parameters for fine-tuning, and re-plotting. The end-user can re-draw and further explore the model data for statistical analysis. My input above only consolidates this fact!

Regards,
