### ISSUE TITLE
3D raypath result of the seismic tomography inversion

### ISSUE THREAD

**Issue by siam2015** [gimli-org/gimli#404]
### Problem description

I wanna plot the ray paths based on a 3D taveltime inversion result. I found that the tt.drawRayPaths is not work in 3D because of the absent plotter. And the code in the example of "Refraction in 3D" is also not of my case, because the plotted ray path is recalculated by the Dijkstra forward model according to the inverted slowness, which is not the real raypaths used in the inversion process. Thus my question is if it is possible to plot the ray path that used calculated during the inversion? or say is there a function similar to the "drawRayPaths ()" for the 3D inversion result?

### Your environment

**Operating system**: Windows
**Python version**: 3.6
**pyGIMLi version**: latest
**Way of installation**: Conda package

**Comment by halbmy** [comment]
First, there is no recent pyGIMLi version for Python 3.6. We dropped supporting Python 3.6 with version 1.1.1, i.e. more than 2 years ago. On Windows there is currently only Python 3.8. Creating an environment is recommended.

As response to #394, there is a function `getRayPaths` that returns the ray paths so that you can plot them by yourself using mplot, pyVista or whatever. Note that before the next release you will have to git-checkout the dev branch to use this function.

**Comment by siam2015** [comment]
Many thanks for your comments. It perfectly solves my problem by adding the function described in #394. Cheers.
