### ISSUE TITLE
Is there any example to use lsqr in pygimli?

### ISSUE THREAD

**Issue by xichaoqiang** [gimli-org/gimli#428]
The new version of gimli add lsqr function to inversion module.

Is there any example to show how use it in inversion step?

Thanks.

**Comment by halbmy** [comment]
No there is no example and none needed. The inversion will use the LSQR solver instead of the (C++) CGLS in the future. You can already make use of this by using the inversion framework `LSQRInversion` which enables to pose additional equations on the original parameters as described by Wagner et al. (2019) by using block matrices. Otherwise the results are identical to the normal `pg.Inversion`.

Wagner, F.M., Mollaret, C., Günther, T., Kemna, A., Hauck, A. (2019): Quantitative imaging of water, ice, and air in permafrost systems through petrophysical joint inversion of seismic refraction and electrical resistivity data. Geophys. J. Int. 219, 1866-1875. doi:10.1093/gji/ggz402.

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.
