### ISSUE TITLE
Cascade Inversion

### ISSUE THREAD

**Issue by nbillybgkv** [gimli-org/gimli#444]
i am student and döing Cascade inversion for my masters thesis by using the following steps.
1) Load the timestep 1 and invert it as start model   
ert.load=Timestep1 
d1=mgr.invert(Timestep1,verbose=True,mesh=mesh, lam=20)
2) After the inversion of timestep1,load timestep2 and invert it,and take the timestep1 as start model.
ert.load=Timestep2
 d2=mgr.invert(Timestep2, start model=d1, mesh=mesh, lam=20).
Is it the correct way?but the problem i am facing is that the results of cascade inversion and the independent inversion for timestep2 is same.

**Comment by halbmy** [comment]
Yes, the procedure is generally correct. However, in a global minimization the model is only weakly depending on the starting model because the model tends to the smoothest model that is in accordance to the data.

If timestep1 is a reference solution (a baseline) you should additionally pass `mgr.invert(..., isReference=True)` so that the difference (actually the ratio because logarithms are used) between the two models is constrained.
