### ISSUE TITLE
Save extracted resistivity

### ISSUE THREAD

**Issue by Abby123455r** [gimli-org/gimli#476]
I extract the resistivity from the mesh by using the following command.
posVec = [pg.Pos(pos) for pos in zip(x, z)]
resMesh = pg.interpolate(srcMesh=mgr.paraDomain, inVec=mgr.model, destPos=posVec)

Now, i want to save the extracted resistivity to plot it in Excel,how can i save the extracted resistivity results.  

Thank you

**Comment by halbmy** [comment]
The model consists of model cells (e.g. triangles) with piecewise constant resistivity. So any interpolation (I would rather interpolate log-resistivity) will always decrease the gradients and further smooth the model. Instead of interpolation, I suggest using a mapping operator as done in https://www.pygimli.org/_examples_auto/6_inversion/plot_5_ert_with_priors.html
```
fop = PriorModelling(mgr.paraDomain, posVec)
resMesh = fop(mgr.model)
```
At any rate, you have the resistivity at some x, z positions, so you can save it to a text file with
```
np.savetxt("out.txt", np.column_stack((x, z, resMesh)))  # add fmt, delimiter or header keywords
```

**Comment by Abby123455r** [comment]
Thank you.and how we can save the high resolution image section.

**Comment by halbmy** [comment]
> Thank you.and how we can save the high resolution image section.

Which high-resolution image do you mean? If it is the output of the manager, you can do
```
ax, cb = mgr.showResult() # add keywords like cMin,cMax,cMap,logScale etc.
ax.figure.savefig("result.pdf")
ax.figure.savefig("result.png", dpi=300)
```

**Comment by Abby123455r** [comment]
Thank you.
In an example, vertical weighting factor of 0.2 was used.Could you please guied me how it was calculated.

**Comment by halbmy** [comment]
```
mgr.invert(zWeight=0.2)
```

**Comment by Abby123455r** [comment]
Thankyou. But how we calcuate its value is 0.2.on which factors value of vertical weight is depends.

**Comment by halbmy** [comment]
I don't understand your question. `zWeight` is just as `lam` an expectation on the smoothness of your model. It can only be derived and validated with external data, but it might help to look at the misfit distribution, see 
https://www.pygimli.org/_tutorials_auto/3_inversion/plot_8-regionWise.html#sphx-glr-tutorials-auto-3-inversion-plot-8-regionwise-py
