### ISSUE TITLE
VES Inversion question

### ISSUE THREAD

**Issue by JabOussama** [gimli-org/gimli#478]
### Problem description

Hello, please i am using this code to invert VES data
```
import numpy as np
import matplotlib.pyplot as plt

import pygimli as pg
from pygimli.physics import VESManager

ab2, mn, ra = np.genfromtxt("mydata3.dat", unpack=True)
err = np.ones_like(ra) * 0.015
ves = VESManager(ab2=ab2, mn2=mn/2)

model = ves.invert(ra, err, nLayer=3, showProgress=0, verbose=1)

plt.show()
ves.showFit()
```
and I would like to merge the result with the fit. 

I have also a problem because i want to compare with result inversion using IPI2win software but i can not plot the resulting curves like the ipi2win curves shown above in the photo.
Thanks
![allves](https://user-images.githubusercontent.com/120740202/210801493-90e1bccd-dab9-459e-b21a-4b69009f82da.jpg)

**Comment by JabOussama** [comment]
i can't upload the .txt file, so i put the data here
2 1 12.6
4 1 10.7
6 2 9.9
10 2 8.58
15 3 11.1
20 4 13.3
25 5 14.3
30 8 14
40 12 9.41
50 14 8.58
60 12 9.5
70 14 10.6
80 16 11.9

**Comment by halbmy** [comment]
Actually you should be able to pass the axis to the `showFit` or `showData` functions so that it is plotted into the model:
```
ax, cb = ves.showResult()
ves.showFit(ax)
# or ves.showData()
```
![image](https://user-images.githubusercontent.com/7136401/212643277-1b450005-b806-4a35-a5be-28a52c5b136e.png)
There were some inconsistencies that were solved now.

At any rate, you can do your plottings in matplotlib your own style. The response of the model `ves.model` is located in `ves.inv.response`.

**Comment by TheNablaOperator** [comment]
Hello, since there is an open VES question I put that here...
I want to run an 1D inversion as well, but `nLayer` seems to be always 4...

Here a small example, obviously it's homogeneous, but should be ok for the example...
pg-Version: 1.3.1, conda, Win10

```python
ab2 = np.logspace(-1, 2, 50)  
mn2 = ab2 / 3

ra = np.ones_like(mn2)*100;
errPerc = 3
rhoa = ra * (np.random.randn(len(ra)) * errPerc / 100. + 1.)

inv1 = ert.VESManager()
nlay = 3;
model = inv1.invert(rhoa, ab2=ab2, mn2=mn2, nLayer=nlay, showProgress=1,verbose=1)
res, thk = model[nlay-1:nlay*2-1], model[0:nlay-1];

inv1.showResult()
```

**Comment by halbmy** [comment]
Yes, you are completely right, thank you for reporting this one. Apparently we haven't worked with VES for a long time.

**Comment by TheNablaOperator** [comment]
OK. Thanks for the information.
Just another thing, is it in principle possible to make a VES on a 3D model...?
Just like one can do with `ert.simulate()`.

E.g. by building a 3D world with mesh, and then apply `ves.simulate()`?
Currently I get an error: `TypeError: object of type 'Mesh' has no len()`

**Comment by halbmy** [comment]
> OK. Thanks for the information. Just another thing, is it in principle possible to make a VES on a 3D model...? Just like one can do with `ert.simulate()`.
> 
> E.g. by building a 3D world with mesh, and then apply `ves.simulate()`? Currently I get an error: `TypeError: object of type 'Mesh' has no len()`

You mean making a simulation on a 3D mesh? Of course, but you will have to use `ert.simulate` instead, generating a mesh, a resistivity vector etc. And to save the VES into a `pg.DataContainerERT`.

**Comment by TheNablaOperator** [comment]
Hmmm... I created a VES using 
`shm = ert.createData(elecs=np.linspace(start=34.5-i*4.5, stop=34.5+i*4.5, num=4), schemeName='wa')`

I started with 3m spacing (WA) and simulated 7 depths (increasing spacing with 3m). I stored the coordinates and sounding data in one scheme-File, which is attached. 
I guess there is a more easy way ^^

However, when I want to load the data for printing, it seems that there are other array types in it? I would assume only WA and since the middle of the survey is fixed to 34.5m I would assume that the rhoa values are on top of each other... But they look like:

Probably someone has a suggestion, Many thanks!

```Python
survey = ert.load('VES_Full_pg.dat'); 
ert.show(survey, **print_kw)
```

![grafik](https://user-images.githubusercontent.com/62592621/212915793-58563e95-e52a-44b0-a98e-4a35cb05ffa2.png)

[VES_Full_pg.txt](https://github.com/gimli-org/gimli/files/10435636/VES_Full_pg.txt)

**Comment by TheNablaOperator** [comment]
It seems that `ert.load()` misses 1 data point. Although there are 7 rhoa values in the file, the loader recognizes only 6...

**Comment by halbmy** [comment]
When loading `VES_Full_pg.txt` by `ert.load`, one gets the error message:
```
Warning: Duplicated sensor position found at: 30	0	0
Warning: Duplicated sensor position found at: 39	0	0
Warning: Duplicated sensor position found at: 25.5	0	0
Warning: Duplicated sensor position found at: 43.5	0	0
Warning: removed 1 values due to sensor index out of bounds!
Data validity check: found 1 invalid data. 
Data validity check: remove invalid data.
```
The sensor list is a unique list of electrode positions, so there should not be any duplicates. As a result of removing the four duplicate sensors, the last measurement points to non-existing sensors and is thus deleted. This is indeed a shortcoming (bug) as sensor indices should be remapped upon removing duplicates.

**Comment by halbmy** [comment]
After Carstens fix, the issue can be close.
