### ISSUE TITLE
Applying 2d Inversion with MagneticsModelling

### ISSUE THREAD

**Issue by aquiles300** [gimli-org/gimli#481]
I am trying to development a 2d magnetic inversion with physics.gravimetry module. I am doing that by making a 3D thin grid  and follow the https://www.pygimli.org/_examples_auto/4_gravimetry_magnetics/plot_mod-magnetics-3d.html#sphx-glr-examples-auto-4-gravimetry-magnetics-plot-mod-magnetics-3d-py recipe

 I feel it is not working. 

 **Operating system**: Fedora 34
**Python version**: 3.9.15
**pyGIMLi version**: 1.3.1
**Way of installation**: Conda package

my code:

``` 
import pygimli as pg
import numpy as np
import matplotlib.pyplot as plt
import pygimli.meshtools as mt
from pygimli.viewer import pv
from pygimli.physics.gravimetry import MagneticsModelling

#parameter
dx = 10
err=0.1e-9
area=2000
F=35201.14e-9
I=38.81918
D=-2.002166
H=27426.2e-9
X=27409.46e-9
Y=-958.1967e-9
Z=22066.35e-9 
igrf = [D, I, H, X, Y, Z, F]

#read data profiles
X,Y,nT,y0,alt = np.loadtxt('profile_703100.txt', skiprows=1, unpack=True)
x0=np.repeat(0.5*dx,np.size(nT))# at X constant (UTM)
z0=np.repeat(-10,np.size(nT))
points = np.column_stack((x0,y0,z0))
data=pg.Vector(nT*1e-9) #create data
relError=pg.Vector(len(data),err)

#profiles were development at constant X (UTM)
x = np.arange(0., dx+0.1, dx)
y = np.arange(0., 4001, dx)
z = np.arange(0., 501, dx)
grid = pg.createGrid(x, y, z)

#compute model
cmp = ["TFA"]  # ["Bx", "By", "Bz"]
fop = MagneticsModelling(grid, points, cmp, igrf)
model = pg.Vector(grid.cellCount(), 1.0)

#attenuation factor
bz = np.array([b.center().z() for b in grid.boundaries() if not b.outside()])
z0 = 25.0
wz = 1.0 / (bz+z0)**1.5
fop.region(0).setConstraintWeights(wz)

#Inversion method
inv = pg.Inversion(fop=fop, verbose=True)  # , debug=True)
inv.setRegularization(limits=[1e-10, 0.1])  # to limit values
startModel = pg.Vector(grid.cellCount(), 0.001)
invmodel = inv.run(data, relError, lam=10., startModel=1e-4, verbose=True)
grid["inv"] = pg.Vector(invmodel)

#plot
plt.plot(data)
plt.plot(inv.response)
plt.legend(['data','inv'])
plt.show()
```

[profile_703100.txt](https://github.com/gimli-org/gimli/files/10562260/profile_703100.txt)

My problem is that "inv.response" and the original data are not fitting at all. 

![Figure_1](https://user-images.githubusercontent.com/62153506/216181534-133c4e84-ce70-4275-8573-098919b8d615.png)

Please, help me

**Comment by halbmy** [comment]
Sorry for meddling in so lately. I highly appreciate your efforts in establishing 2D magnetics as it could really widen the coverage of pyGIMLi usage, particularly for teaching and example purposes. Even though I think we need a 2D forward solver, this is a nice chance to step into the matter.

I just realized you generate a starting model
```
startModel = pg.Vector(grid.cellCount(), 0.001)
```
but you don't use it:
```
invmodel = inv.run(data, relError, lam=500., startModel=1, verbose=True)
```
Any reason for that?

Second, if you want to do a 2D inversion, the model should be much wider in x direction (right now only 10m) to account for 2D conditions. Otherwise you will need much bigger susceptibility values to account for the missing volume. I am not sure if there is a numerical problem with elongated hexahedra, if yes, we could divide this into many small ones and treat every row as a single region, i.e. doing a 2D inversion with a 3D forward modelling.

**Comment by halbmy** [comment]
Additionally, the model should be a bit wider than the data in y direction and maybe the depth is not enough. I've played a bit with it and put the profile on x=0 in the middle of a 500 wide model.

Main point, however, is the error model. First, suggest adding a fixed relative error, because otherwise the inversion tries to fit near-zero values much stronger. And considering the anomalies, I think 0.1nT might be a good number of repeatability, but not realistic about how well we can explain the data in a range of several hundreds of nT. Changing this goes into the right direction:
![image](https://user-images.githubusercontent.com/7136401/217763512-cc8888a1-4d67-450b-8cc3-1a27364c493e.png)

Here is my code that also displays the model as 2D section:
![image](https://user-images.githubusercontent.com/7136401/217763627-cde540a8-0d65-4a40-b7e3-c8794a7b1060.png)

I think the rest could be further tuning with the model extension, error model and inversion settings.
```
"""Issue 481: 2D magnetics inversion."""
import pygimli as pg
import numpy as np
import matplotlib.pyplot as plt
from pygimli.physics.gravimetry import MagneticsModelling

# %% parameters
dx = 10
err = 0.1e-9
area = 2000
F = 35201.14e-9
I = 38.81918
D = -2.002166
H = 27426.2e-9
X = 27409.46e-9
Y = -958.1967e-9
Z = 22066.35e-9
igrf = [D, I, H, X, Y, Z, F]  # you might better use the pyIGRF package for that
# %% read data profiles and simplify it
X, Y, nT, y0, alt = np.loadtxt('profile_703100.txt', skiprows=1, unpack=True)
x0 = np.zeros_like(nT)
z0 = np.ones_like(nT) * (-10)
points = np.column_stack((x0, y0, z0))
data = pg.Vector(nT*1e-9)  # create data

# profiles were development at constant X (UTM)
# x = np.arange(0., dx+0.1, dx)
x = np.array([-250., 250.])
y = np.arange(-500., 4501, dx)
z = np.arange(0., 701, dx)
grid = pg.createGrid(x, y, z)

# compute model
cmp = ["TFA"]  # ["Bx", "By", "Bz"]
fop = MagneticsModelling(grid, points, cmp, igrf)
# attenuation factor
bz = np.array([b.center().z() for b in grid.boundaries() if not b.outside()])
z0 = 25.0
wz = 1.0 / (bz+z0)**1.5
fop.region(0).setConstraintWeights(wz)
# %% Inversion method
err = 3e-9
relError = pg.Vector(err/np.abs(data)) + 0.01
inv = pg.Inversion(fop=fop, verbose=True)  # , debug=True)
# inv.setRegularization(limits=[1e-10, 0.1])  # to limit values
inv.setRegularization(limits=[0.001, 1.5])  # to limit values
# startModel = pg.Vector(grid.cellCount(), 0.001)
invmodel = inv.run(data, relError, lam=100., startModel=1, verbose=True)
grid["inv"] = pg.Vector(invmodel)
grid.exportVTK("inv.vtk")
# %%
grid2d = pg.createGrid(y, -z)
pg.show(grid2d, invmodel, logScale=True, cMap="Spectral_r")
# %% plot
fig, ax = plt.subplots()
ax.plot(y0, data*1e9, label="data")
ax.plot(y0, inv.response*1e9, label="inv")
ax.grid()
ax.legend()
```

**Comment by aquiles300** [comment]
Hey Gunther, it works

![Figure_1](https://user-images.githubusercontent.com/62153506/217956717-e297a2bf-5a80-4c51-94a9-0cab618565b3.png)

Now I want to introduce topography. I believe I can do it with the appropriated mesh. 

Thank you

**Comment by halbmy** [comment]
Great!

For including topography, you will have to create a 2D mesh first, by functions like `mt.createParaMesh` and then extrude it into the third dimension by `mt.extrudeMesh` (`import pygimli.meshtools as mt`). See meshtool documentation and examples. Would be great to see the solution here and to have an example eventually.

**Comment by halbmy** [comment]
By the way, what did you have to change to obtain the good model fit?

Nevertheless I am wondering about the results, which display susceptibility. The values seem very high to me, even if you disregard the two extremely high anomalies. Is there any scale issue?

**Comment by aquiles300** [comment]
Hello Gunther,

I am working with the next parameters

```
z0 = -5
dx = 20
area = 2000
err = 1e-9   #absolute error
derr = 0.001 #minimum relative error
lam = 100.0
startModel = 1.0
suslim = [-100.5,100.5]  #susceptibility range
dPhi = 0.5
maxIter = 100
```
This yield a chi² = 312.88 

I tried to tune the susceptibility range using a lower one (-10.0,10.0), which seems to yield a very little worse solution (chi² = 402.65):

![Figure_1](https://user-images.githubusercontent.com/62153506/218568514-4ecd8c5e-032e-4efe-85c8-64ce17132571.png)


The others parameter (neither 'lamb' nor 'derr') seems not improve enough the solution. 

I dont know what other parameters I can to tune to improve the model.

**Comment by halbmy** [comment]
Seems like `suslim` was not passed to the inversion or is not taken as there are only positive values. I have no idea whether you can expect negative values (diamagnetic material) in this area or which values are meaningful. Typically you have values in the range of 1e-5 to 1e-3, therefore I wondered about the high levels.

There is no such parameter as `lamb` or `derr` (a relative error of 0.001=0.1% seems too low to me anyway). You would have to paste your code so that I can see whether you used it correctly.

**Comment by aquiles300** [comment]
Ok, It is my code

```
import pygimli as pg
import numpy as np
import matplotlib.pyplot as plt
import pygimli.meshtools as mt
from pygimli.viewer import pv
from pygimli.physics.gravimetry import MagneticsModelling

#parameters
z0 = -2
dx = 20
err = 1e-9   #absolute error
derr = 0.001 #minimum relative error
lam = 100.0
startModel = 1.0
suslim = [-100.5,100.5]  #susceptibility range
dPhi = 0.5
maxIter = 100

#igrf model
F = 35201.14e-9
I = 38.81918
D = -2.002166
H = 27426.2e-9
X = 27409.46e-9
Y = -958.1967e-9
Z = 22066.35e-9
igrf = [D, I, H, X, Y, Z, F]

#read data profiles
X,Y,nT,y0,alt = np.loadtxt('profiles/profile_703100.txt', skiprows=1, unpack=True)
x0 = np.zeros_like(nT)
z0 = np.ones_like(nT) * z0
points = np.column_stack((x0,y0,z0))
data=pg.Vector(nT*1e-9) #create data
relError=pg.Vector(err/np.abs(data)) + derr #relative error

#make 3d mesh
#profiles were development at constant X (UTM)
x = np.array([-250., 250.])
y = np.arange(-500., 4501, dx)
z = np.arange(0., 701, dx)
grid = pg.createGrid(x, y, z)
print(grid)

#compute model
cmp = ["TFA"]  # ["Bx", "By", "Bz"]
fop = MagneticsModelling(grid, points, cmp, igrf)

#attenuation factor
bz = np.array([b.center().z() for b in grid.boundaries() if not b.outside()])
z0 = 25.0
wz = 1.0 / (bz+z0)**1.5
fop.region(0).setConstraintWeights(wz)

#Inversion method
inv = pg.Inversion(fop=fop, verbose=True)  # , debug=True)
inv.setRegularization(limits=suslim)  # to limit values
invmodel = inv.run(data, relError, lam=lam, startModel=startModel, verbose=True, dPhi=dPhi,maxIter = maxIter)
grid["inv"] = pg.Vector(invmodel)
grid.exportVTK("inv.vtk") #writing in inv.vtk file

#Plotting models
figsize = [8.7, 5]
f, ax = pg.plt.subplots(2,1,figsize=figsize)
#first
ax[0].plot(y0, data*1e9, label="data")
ax[0].plot(y0, inv.response*1e9, label="inv")
ax[0].grid()
ax[0].legend()
#second
extent = 0.0, 400.0, min(-z), max(-z)
grid2d = pg.createGrid(y, -z)
pg.show(grid2d, invmodel, logScale=True, cMap="Spectral_r",ax=ax[1])
ax[1].set_xlim(0.0,4000.0)
# %% plot
pg.wait()
```

**Comment by aquiles300** [comment]
On the other hand, I got the 3d mesh to apply topography, but I have an inconvenient with that. To yield the 3d mesh, I generated a 2d mesh using yz coordinates (the profile was at X UTM constant) 

```
#read data profiles
X,Y,nT,y0,h0 = np.loadtxt('profile_703100.txt', skiprows=1, unpack=True)
x0 = np.zeros_like(nT)
z0 = np.ones_like(nT) * z0
points = np.column_stack((x0,y0,z0))
data=pg.Vector(nT*1e-9) #create data
relError=pg.Vector(err/np.abs(data)) + derr #relative error

 #mesh parameters
dx = 250.0
area = 100000
quality = 34.3
smooth = [1, 10]
delty = 100.0
deltz = 700.0 #maxima depth
#polygonal points
maxy= max(y0) + delty
miny = min(y0) - delty
maxz = max(h0)
minz = maxz - deltz
y = [maxy,maxy,miny,miny]        #add points to close the polygon
z = [h0[len(h0)-1],minz ,minz ,h0[0]] #add points to close the polygon
y = np.append(y0,y)
z = np.append(h0,z)
rows, cols = (np.size(z),2)
patch = np.asarray([[0]*cols]*rows)
patch[:,0]=y
patch[:,1]=z
#creating 2d grid
geom= mt.createPolygon(patch,isClosed=True, marker=1, area=area)
pg.show(geom)
mesh = mt.createMesh(geom, quality=quality, area=area, smooth=smooth)
pg.show(mesh)
```
it works
![Figure_2](https://user-images.githubusercontent.com/62153506/218846271-dcefd1c9-0921-4e19-ba60-6da9a52dfdce.png)

Now, I applied _extrudeMesh_ 


```
#expand to a 3d mesh
x = np.array([-dx, dx])
grid = pg.meshtools.extrudeMesh(mesh, a=x)
```

![Screenshot from 2023-02-14 13-44-28](https://user-images.githubusercontent.com/62153506/218847119-11844c68-f732-4222-a47a-c02eafb5bbf1.png)

It seems to be fine, but, as I extended to the third dimension by 'x', for the grid it is the 'z' dimension. More than that, 'y' is taken as 'x', and 'z' is taken as 'y'. 

I think that I could inter-change axis of data points and igrf for the inversion, but, it doesnt sound like a sofisticate solution. Is there some way to indicate the axis to the mesh (not for the plot but for the interpretation of axis dimension of the grid)? I didnt find how to do that in the meshtool documentation.

**Comment by aquiles300** [comment]
Sorry, I found that _swapCoordinates_ do exactly I want. Axis are correct now.

I feel a bit silly

**Comment by halbmy** [comment]
Sorry for getting back to this so lately. The current implementation of the grav/mag kernel does not work for triangular prisms as created by `extrude`, but only tetrahedra or hexahedra. You would have to split the prisms (maybe just use two planes for `x`) in tetrahedra by piping it into tetgen. However, I don't consider this efficient as one additionally needs a very large y axis. A real 2D magnetics code would be needed but there should be codes around. The particular solution seems an edge case to me which is why I close this issue.
