### ISSUE TITLE
The mesh marker problem

### ISSUE THREAD

**Issue by geohang** [gimli-org/gimli#507]
### Problem description

I am trying to make a region with marker=2, but it gives 0, which is really strange.

### Your environment

Please provide the output of `print(pygimli.Report())` here. If that does not
work, please give provide some additional information on your:

**Operating system**: Windows
**Python version**:  3.8
**pyGIMLi version**: 1.2.6
**Way of installation**: Conda package

### Steps to reproduce
See the figure

![image](https://user-images.githubusercontent.com/75149424/224433485-fef9a276-ddfc-4167-a5dd-c7ec5146ed88.png)

### Expected behavior

I am going to make this region marker 2.

### Actual behavior

The region shows marker 0 instead.

Thank you very much!

**Comment by halbmy** [comment]
Can you provide the matrix that you feed into `mt.createPolygon` so that we can check?

**Comment by geohang** [comment]
Sure! Thank you for the quick reply. I attached the txt file. Thank you!
[geometry.txt](https://github.com/gimli-org/gimli/files/10964047/geometry.txt)

**Comment by halbmy** [comment]
This is indeed a shortcoming in computing the region marker position (`plc.regionMarkers()[0]`) which is with
```
RVector3: (67.29571407745638, -13.028848241372263, 0.0)
```
outside of the polygon. It is currently computed by going 1mm from the first node (right upper point) towards the center of the polygone and since the slope is so high it is slightly outside.
If you use `mt.createPolygon(mat[::-1], ...` it is inside
```
RVector3: (67.2958937599263, -42.683513410859454, 0.0)
```
and the polygon gets the correct marker 2. 

Note that you can also set the marker position by `mt.createPolygon(mat, markerPosition=[30, -30], ...`.

**Comment by halbmy** [comment]
Note that the marker position will be shown (from the next version on):
![image](https://user-images.githubusercontent.com/7136401/224922319-ef2c0798-3808-4426-bf87-aed689cd0fd3.png)
but it is hardly to be seen in your case even after zooming
![image](https://user-images.githubusercontent.com/7136401/224923237-1138dfea-e17e-492b-bcad-0be006c1da56.png)

**Comment by geohang** [comment]
Got it. Thank you so much
