### ISSUE TITLE
Errors during 3D inversion

### ISSUE THREAD

**Issue by ccpipxia** [gimli-org/gimli#523]
### Problem description

Hello!,I conducted a forward simulation in Pygimli and imported the data into the inversion model to make a simple 3D inversion attempt, but the final inversion code encountered an error and I couldn't find the cause of the error.

Error code：
`model_res = mgr.invert(mesh=mesh_inversion,verbose=True)`

error：
`potential matrix rowsize to small.39 < 40`

complete code：
```
import matplotlib.pyplot as plt
import pygimli as pg 
import numpy as np
import pygimli.meshtools as mt
from pygimli.physics import ert

for_1 = mt.createCube(size=[40, 20, 20],pos=[0, 0,10],boundaryMarker=1)
for_2 = mt.createCube(size=[15, 15, 8], pos=[-10, 0,10],boundaryMarker=2)
for_area = for_1 + for_2
#ax,_=pg.show(for_area, alpha=0.3,markers=True)

n_sensor = 40
sensor = np.zeros((n_sensor, 3))
sensor[0:, 0] =np.linspace(10,-10, n_sensor)
sensor[0:,2]=20

for pos in sensor:
    for_area.createNode(pos)
    for_area.createNode(pos - [0.01,0.01,0.01])


mesh_forward = mt.createMesh(for_area,area=5) 
ax,_=pg.show(mesh_forward,showMesh=True,)
#ax=drawSensors(plotter, sensor, diam=0.5, color='yellow')
ax, _ = pg.show(mesh_forward, alpha=0.5,showMesh=True,filter={'clip':{'normal':(0, 0.05, 0),'origin':(0, 0, 0)}})

scheme = ert.createData(sensor,schemeName='dd')

rhomap=[[1, 300],
        [2, 100]]   

data = ert.simulate(mesh_forward, scheme=scheme, res=rhomap, noiseLevel=1,
                    noiseAbs=1e-6, seed=1337
                   )

plt.plot(data['rhoa'])
plt.xlabel('x')      
plt.ylabel('y')

re_1 = mt.createCube(size=[40, 20, 20],pos=[0,0,10])
re_area =re_1
mesh_inversion=mt.createMesh(re_area)
mgr = ert.ERTManager(data)
model_res = mgr.invert(mesh=mesh_inversion,verbose=True)
```

**Comment by halbmy** [comment]
The error looks like one of the 40 electrodes is outside of the mesh. I don't quite understand the type of geometry you are trying to simulate, but for a real-world (half-space) your model needs to be much bigger and it is recommended to create it by `mt.createWorld` instead of creating a cube because it ensures correct boundary conditions. Please have a look at the synthetic 2D examples.

**Comment by ccpipxia** [comment]
Hello Thomas, thank you very much for your answer.But why is there an electrode outside the grid? The size of the inversion region and the forward region I created are actually the same, I looked at the electrode position in the data and no electrode crossed the inversion region.`data.sensorPosition(pos)`

 And I created nodes at the electrode position, changed the length of the measurement line, and the number of electrodes, but none of them worked, and I got the same error when inverting.

**Comment by halbmy** [comment]
I created a notebook for it (3D images are not shown in github):
https://github.com/gimli-org/notebooks/blob/main/issues/523/issue523.ipynb

It reveals two main issues:
1. the mesh has only cell marker 1, i.e. you are modelling a homogeneous halfspace of 300 Ohmm), reason is that you used `boundaryMarker?  instead of (cell) `marker`.
2. Even though the model is homogeneous, the modelled apparent resistivity deviates from 300 towards the end of the profile due to boundary effects

So you should use a larger mesh (and fit the cube with the correct marker in), but you should rather do it with `mt.createWorld`. I suggest to use z=0 for the Earth's surface with z pointing upward.

Main point for your error, however, is of course that the sensors are no nodes in your inversion mesh. Your code
```
re_1 = mt.createCube(size=[40, 20, 20],pos=[0,0,10])
re_area =re_1
mesh_inversion=mt.createMesh(re_area)
```
yields (`print(mesh_inversion)`) a very simple box:
```
Mesh: Nodes: 9 Cells: 8 Boundaries: 23
```
where you cannot find 40 different electrodes. Use print and show commands to inspect your objects.

**Comment by ccpipxia** [comment]
Hello Thomas, I have received your email and received a late response due to the need to modify the code. Firstly, thank you very much for your suggestion. Secondly, regarding the error caused by the sensor not being on a node in the grid, I refined the grid  `mesh_inversion=mt.createMesh(re_area,area=10)` in the code and created a node in the sensor position.Currently, there are 10881 grids in the inversion area, but it still made an error.I will submit the code file.
[3Dinversion.zip](https://github.com/gimli-org/gimli/files/11259724/3Dinversion.zip)

**Comment by ccpipxia** [comment]
Hello Thomas, I have received your email and received a late response due to the need to modify the code. Firstly, thank you very much for your suggestion. Secondly, regarding the error caused by the sensor not being on a node in the grid, I refined the grid&nbsp;in the code and created a node in the sensor position.Currently, there are 10881 grids in the inversion area, but it still made an error.I will submit the code file.


mesh_inversion=mt.createMesh(re_area,area=10)
Mesh: Nodes: 2485 Cells: 10881 Boundaries: 23081
I've made the same comment on github.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gimli-org/gimli"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月18日(星期二) 下午3:58
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [gimli-org/gimli] Errors during 3D inversion (Issue #523)





 
I created a notebook for it (3D images are not shown in github):
 https://github.com/gimli-org/notebooks/blob/main/issues/523/issue523.ipynb
 
It reveals two main issues:
  
the mesh has only cell marker 1, i.e. you are modelling a homogeneous halfspace of 300 Ohmm), reason is that you used boundaryMarker?  instead of (cell) marker`.
 
Even though the model is homogeneous, the modelled apparent resistivity deviates from 300 towards the end of the profile due to boundary effects
  
So you should use a larger mesh (and fit the cube with the correct marker in), but you should rather do it with mt.createWorld. I suggest to use z=0 for the Earth's surface with z pointing upward.
 
Main point for your error, however, is of course that the sensors are no nodes in your inversion mesh. Your code
 re_1 = mt.createCube(size=[40, 20, 20],pos=[0,0,10]) re_area =re_1 mesh_inversion=mt.createMesh(re_area)  
yields (print(mesh_inversion)) a very simple box:
 Mesh: Nodes: 9 Cells: 8 Boundaries: 23  
where you cannot find 40 different electrodes. Use print and show commands to inspect your objects.

**Comment by ccpipxia** [comment]
[3Dinversion.zip](https://github.com/gimli-org/gimli/files/11259838/3Dinversion.zip)

**Comment by halbmy** [comment]
I meant you should add the sensors as nodes to the inversion mesh like you did for the forward mesh.

**Comment by ccpipxia** [comment]
Did I make a mistake in doing this? I don't quite understand what you mean, can you please express it in the code.
![image](https://user-images.githubusercontent.com/130828987/232758156-863d4d4d-faa9-4180-b662-8caf98028220.png)

**Comment by halbmy** [comment]
This sounds good, although such a small refinement is not necessary.

As mentioned above, better use `mt.createWorld` to create a model domain with correct boundary conditions that will allow for secondary field computation.

**Comment by ccpipxia** [comment]
Hello Thomas, the code in the above image is something I tried during the 3D inversion process. You can find it in the zip file, but the inversion process still made an error, which is the same error. Is there any key point that I overlooked? The workflow of this 3D inversion is modeled after 2D inversion, but 2D inversion can work normally. Thank you very much for your patient answer, but the problem has not been resolved yet.

**Comment by halbmy** [comment]
In the notebook from the zip file you did not take any of my comments into account.

I guess the point is that you are modelling in a bounded domain (since you are not taking createWorld). In order to be able to solve for single current injections, one electrode is taken as reference electrode, so I guess this is missing in the potential matrix, but I am not 100% sure. Please improve the notebook first as recommended.

**Comment by ccpipxia** [comment]
Based on your suggestion, modify the code that builds the inversion area. Yes, you are right, inversion can be carried out.
`mt.createWorld(start=[20, -10, 0],end =[-20,10,20])`
