### ISSUE TITLE
pg.Inversion does not work with pg.physics.ert.ERTManager 

### ISSUE THREAD

**Issue by andpalacios** [gimli-org/gimli#547]
### Problem description

Hello,

I have done many trials to use the pg.Inversion module in PyGIMLi and have not succeded because my simulations were run with ert.ERTManager. 
I am not interested in using ert.ERTManager.invert because it doesn't have all the inversion keywords that I would like to use. 

Now, the pg.Inversion needs a forward operation of type MeshModelling. 

Which forward operator should I use then to run my ERT simulations and be able to use pg.Inversion? 
If you could explain how all the modelling classes work it would be very helpful.

Thank you in advance for your help!

Best regards,
Andrea 

### Your environment

Please provide the output of `print(pygimli.Report())` here. If that does not
work, please give provide some additional information on your:

**Operating system**: Windows 
**pyGIMLi version**: 1.4.1
**Way of installation**: conda

### Piece of code

**data = pg.load("./modelled_ert.dat")
mesh = pg.Mesh('mesh.bms')

mgr = ert.ERTManager(data, verbose=True)
mgr.setMesh(mesh) 

tData, tModel = pg.trans.TransLog(), pg.trans.TransLogLU(0.001, 20000.)

inv = pg.Inversion(data=data('rhoa'), mesh= mesh, verbose=True)
inv.setForwardOperator(???) <--- HERE IS MY ISSUE, I DON'T KNOW HOW TO DEFINE THE FOP. 
inv.setRegularization(zWeight=0.1)
inv.setLambda(10000.0)
inv.setLambdaFactor(0.8)
inv.setLineSearch(False)
inv.setBlockyModel(False)
inv.setRobustData(True)
inv.setVerbose(True)
inv.setMaxIter(20)
inv.setRelativeError(data('err'))
inv.modelTrans = tModel 
inv.dataTrans = tData

model_inv = inv.run()**

**Comment by carsten-forty2** [comment]
You can try `mgr.fop` or even more easy use `mgr.inv`.. which is if type pg.Inversion. Creating an own Inversion instance can be tricky since you need to take care of the mesh refinement and renumbering for the forward calculation. The Manager should do it for you .. you allways can look into his implementation to see what he is doing.

However,  It seems you try to mix methods of `pg.Inversion`  which is `mgr.inv` and `pg.core.RInversion` which is `mgr.inv.inv`. We don't recommand any communication with the underlaying `pg.core.RInversion` instance, because it will be removed by a pure python version in the not so far future. Please look here: https://www.pygimli.org/pygimliapi/_generated/pygimli.frameworks.html#pygimli.frameworks.Inversion or in the code directly, which control option for `mgr.inv` do you miss. Let us know if you miss an option and we try to add them.

**Comment by andpalacios** [comment]
Thank you! I'll try to use the mgr.inv. I have managed to get it running now with some keywords. 

I haven't seen the data transformation to logarithm as a keyword in the mgr.inv class. (tData, tModel = pg.trans.TransLog(), pg.trans.TransLogLU(0.001, 20000.); inv.modelTrans = tModel; inv.dataTrans = tData)

I haven't seen either how to set the regularization type (0, 1, 10, 20...)

**Comment by carsten-forty2** [comment]
logarithmic model and data transform are defaults for the ERTManager.

For setting regularization types you could consult one of the newer tutorials, e.g.:
 
https://www.pygimli.org/_tutorials_auto/3_inversion/plot_5_Regularization.html#sphx-glr-tutorials-auto-3-inversion-plot-5-regularization-py

**Comment by andpalacios** [comment]
Thank you very much for your help.
I think I have everything I need now :)
Best,
Andrea
