### ISSUE TITLE
Log Resisitvity and ERT Cross Section

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#554]
I have resistivity log data that I want to bind with resistivity cross section data taken from the surface. 
Is there a script that can be used to bind it? The binding here is just to connect the cross section results. so maybe the first layer is the cross section and the second layer is the resistivity log.
And also is there a function to do inversion on the log data? Because in the logs I have there are long readings and short electrodes and I want to try to make the cross section 2D with n=2. 

Thank you.
[Log Resisitvity Data.csv](https://github.com/gimli-org/gimli/files/11937069/Log.Resisitvity.Data.csv)

**Comment by halbmy** [comment]
What do you mean with *cross section data*? A subsurface resistivity distribution or crosshole (or hole-to-surface) data ?

What exactly do you mean with *bind*? 

Incorporating as prior data? If yes, this example may help: https://www.pygimli.org/_examples_auto/6_inversion/plot_5_ert_with_priors.html

**Comment by halbmy** [comment]
Your data seems to have a long and a short normal (borehole tool), I guess measured in an open hole? I don't think it makes sense to use these data as priors (as done for direct push by Grünenbaum et al. 2023), because they do not represent true resistivities, but are affected by the borehole fluid (Doetsch et al. 2010), the disturbed zone etc. But maybe these data can be added as pole-pole ERT data to the inversion, also taking into account the borehole itself.

References:
Grünenbaum, N., Günther, T., Greskowiak, J., Vienken, T., Müller-Petke, M. & Massmann, G. (2023): Salinity distribution in the subterranean estuary of a meso-tidal high-energy beach characterized by Electrical Resistivity Tomography and Direct Push technology. J. of Hydrol. 617, 129074, doi:10.1016/j.jhydrol.2023.129074.
Doetsch, J., Coscia, I., Greenhalgh, S., Linde, N., Green, A. & Günther, T. (2010): The borehole-fluid effect in
electrical resistivity imaging. Geophysics 75(4), F107-F114, doi:10.1016/j.jappgeo.2011.04.008.

**Comment by tonapawilliam** [comment]
Thank you for providing me with research references.

Sorry, my English is not very good. Maybe I didn't mean to bind, but rather to display my borehole data side by side with my inverse cross section (ERT), as in the example you gave of structured and unstructured mesh formation. And regarding the short and long readings, it is not as prior data but as companion data to the existing ERT data. So since there are short and long readings, where the datum positions are vertically only a few centimeters apart, I wonder if pygimli can form a vertical inversion cross section based on that data.

**Comment by halbmy** [comment]
Ok what you mean is the function:
```
pygimli.viewer.mpl.draw1DColumn(ax, x, val, thk, width=30, ztopo=0, cmin=1, cmax=1000, cmap=None, name=None, textoffset=0.0)
```
https://www.pygimli.org/_modules/pygimli/viewer/mpl/modelview.html#draw1DColumn

`x` is the position, `val` the value vector, `thk` the thickness vector (`np.diff(z)`) and `ax` the axis, e.g.
```
kw = dict(cMin=xx, cMax=yy)
ax, cb = mgr.showResult(**kw)
pg.viewer.mpl.draw1DColumn(ax, res, np.diff(z), **kw)
```

**Comment by halbmy** [comment]
Note that I added an exemplary use of the function in one of the examples:
http://dev.pygimli.org/_examples_auto/6_inversion/plot_5_ert_with_priors.html

However, I had to rename some of the keyword arguments which will be active in the upcoming version v1.4.3. Until then it is still `cmin` instead of `cMin`.

**Comment by tonapawilliam** [comment]
Thank you very much for adding it, now I understand more about the example of using the viewer function. Thank you very much again
