### ISSUE TITLE
Change Parameter Y-Axis in Show Data

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#568]
Excuse Me Sir,

In pygimli, is there any paramater to change the ÿ-axis? I want the y-axis become depth paramater, not the scheme.

![image](https://github.com/gimli-org/gimli/assets/126912836/2a4f81da-3b13-487a-b3d5-23f25c63d9dd)

**Comment by halbmy** [comment]
A pseudosection is a coloured table of measurements. Any pseudodepth can be misleading particularly when a mix of different arrays is used that we plot below each other like in the prior-ERT example
![image](https://github.com/gimli-org/gimli/assets/7136401/a7a4a3ea-d2f5-413d-b274-e50c2eda1c28)

Drawing contour lines of pseudodepth (where WA and SL are mixed into each other) would lead to irregular data representation.


Of course you can write whatever you want on the axis labels
```
ax, cb = showXXX(...
ax.set_yticklabels(...
```

**Comment by halbmy** [comment]
Furthermore: When writing a depth at the y axis, non-experts tend to do interpretation of the pseudosection which can be very misleading. Therefore I like to represent a pseudosection as a well-sorted data table with each data point being represented by the same area.

**Comment by tonapawilliam** [comment]
Thank you, sir, can you give one example and scipt code about plotting observed data with y Axis-Depth Parameter in meters? You can use this data
[3a.txt](https://github.com/gimli-org/gimli/files/12344477/3a.txt)

**Comment by carsten-forty2** [comment]
To change the ticklabels for the y-axis you can use the code fragment @halbmy provided in his post. However, you need decide yourself which values you want to choose as depth values for your datapoints. 

As @halbmy mentioned above, there is no fixed depth value for a measured data value. Since a 4-point-measurement is integral over the whole domain covered by the electrode extends, you only can assume an approximated mean depth. Beside the electrode extent, this depth value might also depend on the used measurement scheme as well on the local resistivity distribution in the ground. Assumed depth values for colored table of measured data are usual wrong and lead unexperienced users to missinterpretations, so we avoid it and don't provide any function for it. 

Note, one can argue the same for the x-axis since there is also no exact horizontal position for a data value. However, the middle position of a 4-point-measurement is not a bad approximation for such pseudosections, so we  use it for such images. Pseudosections are only images for quality assurance and should never be used for any interpretations.

**Comment by tonapawilliam** [comment]
Perhaps to clarify the issue I want to question. I received a paper on the use of pygimli. Here is the link and some pictures in the paper.
[(https://www.researchgate.net/publication/362263536_Open-source_learning_as_a_skill_for_geoelectrical_data_processing_the_case_of_pyGIMLi)](url)
![image](https://github.com/gimli-org/gimli/assets/126912836/79c9781e-62c3-4d68-92f6-772f4023212f)
![image](https://github.com/gimli-org/gimli/assets/126912836/028fd68d-2ed9-4243-b486-ed08ecd4475b)
![image](https://github.com/gimli-org/gimli/assets/126912836/c5dbd46f-4bf8-49c8-8ba4-4f4c37ab00c8)

In the measured apparent resistivity picture, he made the picture cut into layers and made the apparent resistivity in the Y-axis to be the thickness of the layer (depth in meter). I would like to ask for help on how to create the right script to do that. I still don't understand how to use the code you provided.

I want to make the measured apparent resistivity in the Y-axis format as it looks in Res2DInv.
![tempsnip](https://github.com/gimli-org/gimli/assets/126912836/dbb686d6-b072-4e4d-be33-602cc196a180)
