### ISSUE TITLE
Improve resolution computation, provide examples

### ISSUE THREAD

**Issue by florian-wagner** [gimli-org/gimli#58]
`computeR` should take an inversion instance as the (only) argument and account for data weighting, regularization, etc. We also need a minimal example on how to compute model resolution matrices using pygimli.

**Comment by halbmy** [comment]
The inversion will be rewritten in pure Python. Anyway it is not a big issue.

We should also provide resolution matrix (and model covariance) computation as a manager function so that is available for the dummy end user. It just needs to check whether everything is already there in the fop and inv classes.
