### ISSUE TITLE
3D TDIP Simulation

### ISSUE THREAD

**Issue by KianaDamavandi** [gimli-org/gimli#584]
Hi, I would like to do the time-domain IP simulation for a 3D model.

**Comment by halbmy** [comment]
Yes. So what is the question?

In the ERT module, there is an `ERTIPManager` class that you can use for it. You need a mesh, a datacontainer, and the two vectors for resistivity and chargeability:
```
from pygimli.physics import ert
mgr = ert.ERTIPManager()
mgr.simulate(mesh, res, m, scheme)
```

**Comment by halbmy** [comment]
Do you want to work in TD (title of the issue) or FD (your code)? I assume FD. There are several points:

1. The modelling domain should have appropriate boundary markers for the boundary conditions of the forward problem. Yours are 1 and result in an indefinite matrix. You should replace `createCube` by `createWorld`, which creates homogeneous Neumann (no-flow) BC at the top and mixed BC at the outer boundaries:
```
plc = mt.createWorld(start=[0, 0, -20], end=[40, 40, 0], area=1)
```
2. However, as your electrodes go from 0 to 40, your world needs to be much bigger modelling domain because `dataFD.show()` shows clear boundary effects:
![image](https://github.com/gimli-org/gimli/assets/7136401/a49b717d-8cbf-4c30-afe8-d3ed86056835)
3. Your block should be in the subsurface (z<0) and not above:
```
block = mt.createCube(size=[6, 6, 2], pos=[20, 20, -5], marker=2, area=1)
```
4. For tetrahedral meshes, the quality of 33.5 does not make sense. You should use values of about 1.3
5. Providing maximum cell sizes should be done in either the plc or in `createMesh`, not both.
6. Your imaginary part should always be negative (voltage lagging current) to be physically plausible. 
7. Your block is currently 20m outside the profile, so you won't see much of it.

```
plc = mt.createWorld(start=[-100, -100, -100], end=[140, 140, 0], marker=1) # , area=5)
scheme = ert.createData(elecs=pg.utils.grange(start=0, end=40, n=21), schemeName='dd')
block = mt.createCube(size=[6, 6, 2], pos=[20, 20, -5], marker=2, area=2)
plc += block
for start in scheme.sensorPositions():
    _= plc.createNode(start, marker=-99)
    _= plc.createNode(start + [0.0, 0, -0.2])
mesh = mt.createMesh(plc, quality=1.3)  # , smooth=True)
rhomap = [[1, 100 - 0.001j], [2, 50 - 2j]]
dataFD = ert.simulate(mesh, res=rhomap, scheme=scheme, verbose=True)
dataFD.show()
dataFD.show("phia", label="-apparent phase (mrad)")
```

**Comment by halbmy** [comment]
Any progress?

**Comment by KianaDamavandi** [comment]
Thanks for asking. I could get the desired result but now I need to plot the final image smoother (reducing the size of rectangle cells). Do you have any solution for this? Thank you again for your assistance and time. 
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import ert
from pygimli.viewer.mpl import showDataContainerAsMatrix
plc = mt.createWorld(start=[-20, -20, -10], end=[20, 20, 0], marker=1, area=2)
scheme = ert.createData(elecs=pg.utils.grange(start=-10, end=10, n=21), schemeName='dd')
block = mt.createCube(size=[5, 5, 2], pos=[0, 0, -5], marker=2, area=1)
plc += block
for start in scheme.sensorPositions():
    _= plc.createNode(start, marker=-99)
    _= plc.createNode(start + [0.0, 0, -0.2])
mesh = mt.createMesh(plc, quality=1.3)  # , smooth=True)
pg.show(mesh, mesh.cellMarkers(), showMesh=True)
rhomap = [[1, 1.290051930293877e+03 - 4.304514491654190e+02j], [2, 4.192315337624802e+03 - 2.000336844787337e+03j]]
dataFD = ert.simulate(mesh, res=rhomap, scheme=scheme, verbose=True)
dataFD.show()
dataFD.show("phia", label="-apparent phase (mrad)")

**Comment by halbmy** [comment]
Every rectangle represents one data point and the pseudosection is a coloured table of data in which you can identify single points like outliers. I really recommend NOT using any sort of interpolation using some sort of pseudodepth as you're loosing this attribution. For "smaller rectangles" you can only use more electrodes and/or other arrays.
