### ISSUE TITLE
Support python 3.6

### ISSUE THREAD

**Issue by florian-wagner** [gimli-org/gimli#59]
Py3.6 is making its way into the scientific community and is already the new standard for the Anaconda/Miniconda distributions. We should test the manual build/curl script with py3.6 and provide conda py3.6 packages for pygimli 1.0.

**Comment by florian-wagner** [comment]
I have built a Python 3.6 package for conda: https://anaconda.org/gimli/pygimli/files

Can someone please test the following (under Linux):

``` bash
conda install -c gimli pygimli python=3.6
wget http://www.pygimli.org/_downloads/plot-4-dc1dsmooth.py
python plot-4-dc1dsmooth.py
```
Thanks.

**Comment by halbmy** [comment]
Claudio did so (on a virtual box on Mac) and all is running nicely as far as I can observe. 
Thanks for providing the binary.

So we have binaries for the Python versions 2.7, 3.4, 3.5 and 3.6? Is there a counter so that we can see which are used? Maybe we can skip 3.4 and possibly we will have to drop Python 2 support in the near future (1-2 years). As building from the curl script is straightforward we can focus on Python 3.5 and 3.6.

**Comment by halbmy** [comment]
i need to retry building with py3.6 on win

**Comment by carsten-forty2** [comment]
win64, py3.6, gcc 6.3 + boost-1.64 compiles without problem using curl

**Comment by halbmy** [comment]
Thanks Florian and Carsten! I will provide binary installers for py 3.4, 3.5 and 3.6 next week.
