### ISSUE TITLE
Finite Element in ERT

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#700]
Excuse me, Sir. This is something that has made me curious all this time. How to process the simulation with a triangular mesh like this
![Figure_9](https://github.com/gimli-org/gimli/assets/126912836/7a91a54e-542e-49ee-807f-6e03bcf40b44)
can be calculated data like this
![Figure_8](https://github.com/gimli-org/gimli/assets/126912836/b89a4bab-d949-4b7a-81bf-d4547738abd9)

I've always been curious about the formula used in this method. I have a target to try to calculate the forward model of the triangular element method with data using a 10 Wenner array electrode so that it is possible to know how the calculation process is carried out in calculating this 2D potential field.

**Comment by halbmy** [comment]
I don't quite understand your question. The finite element method used for ERT is explained in this example:
https://www.pygimli.org/_examples_auto/3_ert/plot_04_ert_2_5d_potential.html
In your case, you seem to miss appropriate boundary conditions so that the apparent resistivity at the sides and for large penetration goes up (showing the isolating boundaries). Please have a look at the examples to learn about boundary conditions.

**Comment by tonapawilliam** [comment]
Thank You Sir
