### ISSUE TITLE
Seeking Help with 3D Magnetic Inversion

### ISSUE THREAD

**Issue by sayedmahmoud486** [gimli-org/gimli#727]

**Comment by halbmy** [comment]
> where the resulted model doesn't match with the observed magnetic data

model and data are completely different things, how can they match?

If you mean the match between data and model response, you're fitting the data within errors (chi2<1) and the misfit also looks uncorrelated Gaussian. 

So please describe your problem in detail. Note that there is a template to be filled in with information on version, what you expect and what you get. Help others understand your problem so that they can help you.
