### ISSUE TITLE
How to install pyGIMLi for windows user ? 

### ISSUE THREAD

**Issue by Fan022** [gimli-org/gimli#76]
Hello, everyone.
I want to use pyGIMLi for study, so I carried out the installation on windows as the steps provided by official website. But there is a error that no module named 'pygimli' when I run example. I think the reason is that I can't fully understand the meaning of content of installation so that I incorrectly install it . So I hope someone can offer the steps of installation  on windows in the form of pictures and the necessary description.

**Comment by halbmy** [comment]
Dear Fan022,
on https://www.pygimli.org/installation.html#win we provide links to Windows wheels, i.e. binary packages for 64bit Windows versions of Python 3.5 and 3.6. The popular WinPython distribution provides a so-called Control Panel that is located in your WinPython installation:
![grafik](https://user-images.githubusercontent.com/7136401/29315366-3ed94506-81c3-11e7-9507-53dca64488f2.png)
You can select the wheel by clicking on Add packages
![grafik](https://user-images.githubusercontent.com/7136401/29315416-81b8cdc4-81c3-11e7-91e1-b2f74b5ac8fe.png)
It should then show name and version number. Install packages installs it so that you can call Spyder.exe and use pygimli by just importing. This also work from the command line. A new version can just be upgraded by the same steps (the case in my screenshot). If you're using another Python distribution without a Control Panel, just type
```pip install pygimli-1.0rc4-py36-none-win64.whl```
from the place where is it (or with full path from any other place) on the command line.

**Comment by halbmy** [comment]
sorry, the links on the pygimli page seem to go wrong. I corrected it but the website is updated nightly.
In the meanwhile, you can take these links for Python 3.5 and 3.6:
http://www.pygimli.org/distribution/pygimli-1.0rc4-py35-none-win64.whl
http://www.pygimli.org/distribution/pygimli-1.0rc4-py36-none-win64.whl

**Comment by Fan022** [comment]
Thank you very much for your understandable answer.
However,  there still is an error that no module named 'pygimli' when I run example after I did what you said. The followings are some pictures of installation.
1. First, I download the whl file. Then I select the wheel by clicking on Add packages. Then I click on Install packages.  


![qq 1](https://user-images.githubusercontent.com/31031527/29345861-27b83d94-8274-11e7-9892-205ffcaf0359.png)

2. I use pygimli by just importing in Spyder.exe, but an error occurs.

![qq2](https://user-images.githubusercontent.com/31031527/29346139-f926de20-8275-11e7-80eb-a8d1709a5e34.png)

Now I am confused and don't know how to handle it.  I think the emergence of the problem may be related to the setting of path, but I have no ideal about it. So I hope you can continue helping me and tell me the concrete solution.
I would be very grateful for your help.

**Comment by carsten-forty2** [comment]
There is a small issue with the wheel filenames that prevents the installation. 

If you rename `pygimli-1.0rc4-py36-none-win64.whl` to
`pygimli-1.0rc4-py36-none-any.whl`, the installation should work.

We will fix it on the download page. 

Thanks for reporting.

**Comment by Fan022** [comment]
The installation can work after I rename the whl file.
Thank you very much for helping me solve this problem .

**Comment by halbmy** [comment]
I renamed the wheels on the install page to the PEP425compliant names 
(Python=cp36/cp35, ABI=cp36m/cp35m, platform=win_amd64)
so that it should work well.

Additionally I created a Microsoft Installer (MSI) that allows choosing the Python (in case it is not in the PATH) which is why it might be better for Anaconda. However, as a drawback it requires administrator rights.

**Comment by nishantra4** [comment]
Is this will work in a similar way for python 3.7

**Comment by halbmy** [comment]
Yes, of course. We dropped support for Python 3.5 with version 1.0.6 and support Python 3.7 from version 1.0.10 on. See https://github.com/gimli-org/gimli/releases where you can download all files (under assets). The most recent versions are also linked on pygimli.org under Installation.

**Comment by nishantra4** [comment]
Thank you for replying. Now the codes are running smoothly.
