### ISSUE TITLE
Installation using setup.py: ship libgimli.so?

### ISSUE THREAD

**Issue by m-weigand** [gimli-org/gimli#93]
After pygimli is built using `make pygimli`, it can be installed using the setuptools-provided setup.py file with `python setup.py install`. This will install the **_pygimli_.so** file, but not **libgimli.so**. Therefore, **libgimli.so** must be copied manually and the library path still needs to be set in order to use pygimli, e.g. in a virtualenv. Is it possible to also ship pygimli.so next to _pygimli_.so? This should also simplify certain distribution issues. For example, `python setup.py sdist` could be used to distribute and install working versions of pygimli.

**Comment by florian-wagner** [comment]
Hm, as long as libgimli.so still finds its dynamic dependencies, this should work. I'll give it a try.

**Comment by halbmy** [comment]
Despite the term _ship_ you are referring to a local installation (on the same computer), right? 
(Shipping to another computer is achieved by e.g. `python setup.py bdist_conda`)

If installing locally, `make install` (possibly with some DESTDIR= ) is the usual task that makes the libgimli.so available to any possible app (there are not many left) for yourself or all users. I doubt that other packages copy the C++ lib to a Python directory but I could be wrong.

**Comment by florian-wagner** [comment]
It's a design question. Do we *ship* a core library in `/usr/lib` and a python package on top of it in `.../site-packages/` or do we think of `pygimli` as a python package with some compiled parts such as numpy, matplotlib and others.

I think we agree on the latter, but then this is a valid issue, because we are not consequent yet, everything should be self-contained. If you install scipy, which has lots of compiled parts, all files get shipped to the python directories, because it's a **Python** package.

https://packages.debian.org/de/stretch/amd64/python3-scipy/filelist

**Comment by halbmy** [comment]
totally agree, then we should install the .so file as well into the python directory
